// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/provider.proto

package go_micro_srv_provider

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlanInterval int32

const (
	PlanInterval_UNKNOWN PlanInterval = 0
	PlanInterval_DAY     PlanInterval = 1
	PlanInterval_WEEK    PlanInterval = 2
	PlanInterval_MONTH   PlanInterval = 3
	PlanInterval_YEAR    PlanInterval = 4
)

var PlanInterval_name = map[int32]string{
	0: "UNKNOWN",
	1: "DAY",
	2: "WEEK",
	3: "MONTH",
	4: "YEAR",
}

var PlanInterval_value = map[string]int32{
	"UNKNOWN": 0,
	"DAY":     1,
	"WEEK":    2,
	"MONTH":   3,
	"YEAR":    4,
}

func (x PlanInterval) String() string {
	return proto.EnumName(PlanInterval_name, int32(x))
}

func (PlanInterval) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d89ffb406fb9b17, []int{0}
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Active               bool     `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d89ffb406fb9b17, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type CreateProductRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d89ffb406fb9b17, []int{1}
}

func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type CreateProductResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductResponse) Reset()         { *m = CreateProductResponse{} }
func (m *CreateProductResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductResponse) ProtoMessage()    {}
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d89ffb406fb9b17, []int{2}
}

func (m *CreateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductResponse.Unmarshal(m, b)
}
func (m *CreateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductResponse.Marshal(b, m, deterministic)
}
func (m *CreateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductResponse.Merge(m, src)
}
func (m *CreateProductResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductResponse.Size(m)
}
func (m *CreateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductResponse proto.InternalMessageInfo

type Plan struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount               int64        `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string       `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Interval             PlanInterval `protobuf:"varint,5,opt,name=interval,proto3,enum=go.micro.srv.provider.PlanInterval" json:"interval,omitempty"`
	ProductId            string       `protobuf:"bytes,6,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d89ffb406fb9b17, []int{3}
}

func (m *Plan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plan.Unmarshal(m, b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
}
func (m *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(m, src)
}
func (m *Plan) XXX_Size() int {
	return xxx_messageInfo_Plan.Size(m)
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func (m *Plan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plan) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Plan) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Plan) GetInterval() PlanInterval {
	if m != nil {
		return m.Interval
	}
	return PlanInterval_UNKNOWN
}

func (m *Plan) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type CreatePlanRequest struct {
	Plan                 *Plan    `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlanRequest) Reset()         { *m = CreatePlanRequest{} }
func (m *CreatePlanRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePlanRequest) ProtoMessage()    {}
func (*CreatePlanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d89ffb406fb9b17, []int{4}
}

func (m *CreatePlanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlanRequest.Unmarshal(m, b)
}
func (m *CreatePlanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlanRequest.Marshal(b, m, deterministic)
}
func (m *CreatePlanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlanRequest.Merge(m, src)
}
func (m *CreatePlanRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePlanRequest.Size(m)
}
func (m *CreatePlanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlanRequest proto.InternalMessageInfo

func (m *CreatePlanRequest) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

type CreatePlanResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlanResponse) Reset()         { *m = CreatePlanResponse{} }
func (m *CreatePlanResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePlanResponse) ProtoMessage()    {}
func (*CreatePlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d89ffb406fb9b17, []int{5}
}

func (m *CreatePlanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlanResponse.Unmarshal(m, b)
}
func (m *CreatePlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlanResponse.Marshal(b, m, deterministic)
}
func (m *CreatePlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlanResponse.Merge(m, src)
}
func (m *CreatePlanResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePlanResponse.Size(m)
}
func (m *CreatePlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlanResponse proto.InternalMessageInfo

type Customer struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentMethodId      string            `protobuf:"bytes,2,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d89ffb406fb9b17, []int{6}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Customer) GetPaymentMethodId() string {
	if m != nil {
		return m.PaymentMethodId
	}
	return ""
}

func (m *Customer) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type CreateCustomerRequest struct {
	Customer             *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateCustomerRequest) Reset()         { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()    {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d89ffb406fb9b17, []int{7}
}

func (m *CreateCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerRequest.Unmarshal(m, b)
}
func (m *CreateCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerRequest.Marshal(b, m, deterministic)
}
func (m *CreateCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerRequest.Merge(m, src)
}
func (m *CreateCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerRequest.Size(m)
}
func (m *CreateCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerRequest proto.InternalMessageInfo

func (m *CreateCustomerRequest) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type CreateCustomerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCustomerResponse) Reset()         { *m = CreateCustomerResponse{} }
func (m *CreateCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerResponse) ProtoMessage()    {}
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d89ffb406fb9b17, []int{8}
}

func (m *CreateCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerResponse.Unmarshal(m, b)
}
func (m *CreateCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerResponse.Marshal(b, m, deterministic)
}
func (m *CreateCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerResponse.Merge(m, src)
}
func (m *CreateCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerResponse.Size(m)
}
func (m *CreateCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerResponse proto.InternalMessageInfo

type CreateSubscriptionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubscriptionRequest) Reset()         { *m = CreateSubscriptionRequest{} }
func (m *CreateSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSubscriptionRequest) ProtoMessage()    {}
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d89ffb406fb9b17, []int{9}
}

func (m *CreateSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubscriptionRequest.Unmarshal(m, b)
}
func (m *CreateSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubscriptionRequest.Merge(m, src)
}
func (m *CreateSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSubscriptionRequest.Size(m)
}
func (m *CreateSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubscriptionRequest proto.InternalMessageInfo

type CreateSubscriptionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubscriptionResponse) Reset()         { *m = CreateSubscriptionResponse{} }
func (m *CreateSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSubscriptionResponse) ProtoMessage()    {}
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d89ffb406fb9b17, []int{10}
}

func (m *CreateSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubscriptionResponse.Unmarshal(m, b)
}
func (m *CreateSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *CreateSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubscriptionResponse.Merge(m, src)
}
func (m *CreateSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSubscriptionResponse.Size(m)
}
func (m *CreateSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubscriptionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("go.micro.srv.provider.PlanInterval", PlanInterval_name, PlanInterval_value)
	proto.RegisterType((*Product)(nil), "go.micro.srv.provider.Product")
	proto.RegisterType((*CreateProductRequest)(nil), "go.micro.srv.provider.CreateProductRequest")
	proto.RegisterType((*CreateProductResponse)(nil), "go.micro.srv.provider.CreateProductResponse")
	proto.RegisterType((*Plan)(nil), "go.micro.srv.provider.Plan")
	proto.RegisterType((*CreatePlanRequest)(nil), "go.micro.srv.provider.CreatePlanRequest")
	proto.RegisterType((*CreatePlanResponse)(nil), "go.micro.srv.provider.CreatePlanResponse")
	proto.RegisterType((*Customer)(nil), "go.micro.srv.provider.Customer")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.srv.provider.Customer.MetadataEntry")
	proto.RegisterType((*CreateCustomerRequest)(nil), "go.micro.srv.provider.CreateCustomerRequest")
	proto.RegisterType((*CreateCustomerResponse)(nil), "go.micro.srv.provider.CreateCustomerResponse")
	proto.RegisterType((*CreateSubscriptionRequest)(nil), "go.micro.srv.provider.CreateSubscriptionRequest")
	proto.RegisterType((*CreateSubscriptionResponse)(nil), "go.micro.srv.provider.CreateSubscriptionResponse")
}

func init() { proto.RegisterFile("proto/provider.proto", fileDescriptor_0d89ffb406fb9b17) }

var fileDescriptor_0d89ffb406fb9b17 = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xb1, 0xdb, 0x38, 0x13, 0x5a, 0xdc, 0x51, 0x5a, 0x8c, 0xcb, 0x47, 0x64, 0x2e, 0xa1,
	0x50, 0x17, 0xc2, 0xa5, 0xa2, 0x07, 0x54, 0xb5, 0x91, 0x88, 0xaa, 0xa6, 0x91, 0x29, 0xaa, 0x7a,
	0xaa, 0xb6, 0xf6, 0xaa, 0x18, 0xec, 0xb5, 0x59, 0xaf, 0x23, 0xe5, 0xcf, 0x71, 0xe1, 0xce, 0x6f,
	0x42, 0xb1, 0xd7, 0x69, 0x12, 0x92, 0x10, 0x6e, 0x9e, 0xcf, 0xf7, 0xe6, 0xcd, 0xac, 0xa1, 0x91,
	0xf0, 0x58, 0xc4, 0x07, 0x09, 0x8f, 0x07, 0x81, 0x4f, 0xb9, 0x93, 0x9b, 0xb8, 0x7d, 0x17, 0x3b,
	0x51, 0xe0, 0xf1, 0xd8, 0x49, 0xf9, 0xc0, 0x29, 0x83, 0xf6, 0x1d, 0x54, 0xfb, 0x3c, 0xf6, 0x33,
	0x4f, 0xe0, 0x26, 0x54, 0x02, 0xdf, 0x54, 0x9a, 0x4a, 0xab, 0xe6, 0x56, 0x02, 0x1f, 0x11, 0x34,
	0x46, 0x22, 0x6a, 0x56, 0x72, 0x4f, 0xfe, 0x8d, 0x4d, 0xa8, 0xfb, 0x34, 0xf5, 0x78, 0x90, 0x88,
	0x20, 0x66, 0xa6, 0x9a, 0x87, 0x26, 0x5d, 0xb8, 0x03, 0xeb, 0xc4, 0x13, 0xc1, 0x80, 0x9a, 0x5a,
	0x53, 0x69, 0xe9, 0xae, 0xb4, 0xec, 0x3e, 0x34, 0x4e, 0x38, 0x25, 0x82, 0x4a, 0x38, 0x97, 0xfe,
	0xc8, 0x68, 0x2a, 0xf0, 0x10, 0xaa, 0x49, 0xe1, 0xc9, 0xa1, 0xeb, 0xed, 0xe7, 0xce, 0x5c, 0xa6,
	0x4e, 0x59, 0x57, 0xa6, 0xdb, 0x8f, 0x61, 0x7b, 0xa6, 0x63, 0x9a, 0xc4, 0x2c, 0xa5, 0xf6, 0x4f,
	0x05, 0xb4, 0x7e, 0x48, 0xd8, 0x4a, 0x13, 0x8d, 0xf8, 0x46, 0x71, 0xc6, 0x44, 0x3e, 0x8c, 0xea,
	0x4a, 0x0b, 0x2d, 0xd0, 0xbd, 0x8c, 0x73, 0xca, 0xbc, 0x61, 0x3e, 0x49, 0xcd, 0x1d, 0xdb, 0xf8,
	0x11, 0xf4, 0x80, 0x09, 0xca, 0x07, 0x24, 0x34, 0xd7, 0x9a, 0x4a, 0x6b, 0xb3, 0xfd, 0x72, 0x11,
	0xe9, 0x90, 0xb0, 0xae, 0x4c, 0x75, 0xc7, 0x45, 0xf8, 0x0c, 0x40, 0x4e, 0x71, 0x13, 0xf8, 0xe6,
	0x7a, 0xde, 0xbe, 0x26, 0x3d, 0x5d, 0xdf, 0x3e, 0x85, 0x2d, 0x39, 0x59, 0x48, 0x58, 0x29, 0xd4,
	0x01, 0x68, 0x49, 0x48, 0x98, 0x54, 0x69, 0x77, 0x09, 0xa0, 0x9b, 0x27, 0xda, 0x0d, 0xc0, 0xc9,
	0x2e, 0x52, 0x9c, 0xdf, 0x0a, 0xe8, 0x27, 0x59, 0x2a, 0xe2, 0x88, 0xf2, 0xbf, 0x04, 0xda, 0x83,
	0xad, 0x84, 0x0c, 0x23, 0xca, 0xc4, 0x4d, 0x44, 0xc5, 0xd7, 0xd8, 0x1f, 0xd1, 0x2b, 0xd4, 0x7a,
	0x24, 0x03, 0xe7, 0xb9, 0xbf, 0xeb, 0x63, 0x17, 0xf4, 0x88, 0x0a, 0xe2, 0x13, 0x41, 0x4c, 0xb5,
	0xa9, 0xb6, 0xea, 0xed, 0xfd, 0x05, 0x9c, 0x4a, 0x38, 0xe7, 0x5c, 0xe6, 0x77, 0x98, 0xe0, 0x43,
	0x77, 0x5c, 0x6e, 0x1d, 0xc1, 0xc6, 0x54, 0x08, 0x0d, 0x50, 0xbf, 0xd3, 0xa1, 0x24, 0x36, 0xfa,
	0xc4, 0x06, 0xac, 0x0d, 0x48, 0x98, 0x95, 0xbb, 0x2b, 0x8c, 0x0f, 0x95, 0x43, 0xc5, 0xbe, 0x2c,
	0xcf, 0xa0, 0x84, 0x29, 0x05, 0x3b, 0x1a, 0x6d, 0xb0, 0x70, 0x49, 0xd1, 0x5e, 0xfc, 0x83, 0xa0,
	0x3b, 0x2e, 0xb0, 0x4d, 0xd8, 0x99, 0xed, 0x2a, 0x05, 0xdc, 0x85, 0x27, 0x45, 0xe4, 0x73, 0x76,
	0x3b, 0x3e, 0x7b, 0x89, 0x69, 0x3f, 0x05, 0x6b, 0x5e, 0xb0, 0x28, 0xdd, 0x3b, 0x81, 0x87, 0x93,
	0x07, 0x81, 0x75, 0xa8, 0x7e, 0xe9, 0x9d, 0xf5, 0x2e, 0xae, 0x7a, 0xc6, 0x03, 0xac, 0x82, 0x7a,
	0x7a, 0x7c, 0x6d, 0x28, 0xa8, 0x83, 0x76, 0xd5, 0xe9, 0x9c, 0x19, 0x15, 0xac, 0xc1, 0xda, 0xf9,
	0x45, 0xef, 0xf2, 0x93, 0xa1, 0x8e, 0x9c, 0xd7, 0x9d, 0x63, 0xd7, 0xd0, 0xda, 0xbf, 0x54, 0xd0,
	0xfb, 0x92, 0x39, 0x7e, 0x83, 0x8d, 0xa9, 0x37, 0x80, 0xaf, 0x17, 0x8d, 0x38, 0xe7, 0xed, 0x59,
	0x6f, 0x56, 0x4b, 0x2e, 0xd8, 0x23, 0x01, 0xb8, 0xbf, 0x27, 0x6c, 0x2d, 0xaf, 0xbd, 0x3f, 0x5c,
	0xeb, 0xd5, 0x0a, 0x99, 0x12, 0x22, 0x82, 0xcd, 0x69, 0xd5, 0x71, 0x39, 0xc5, 0x99, 0x95, 0x5b,
	0xfb, 0x2b, 0x66, 0x4b, 0xb8, 0x61, 0xf9, 0x42, 0x26, 0xb7, 0x85, 0x6f, 0x97, 0x36, 0x99, 0xb3,
	0x75, 0xeb, 0xdd, 0x7f, 0x54, 0x14, 0xd0, 0xb7, 0xeb, 0xf9, 0x5f, 0xf9, 0xfd, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x5a, 0x9f, 0xd6, 0xdc, 0xad, 0x05, 0x00, 0x00,
}
