// Code generated by protoc-gen-go. DO NOT EDIT.
// source: provider/proto/provider.proto

package go_micro_srv_provider

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlanInterval int32

const (
	PlanInterval_UNKNOWN PlanInterval = 0
	PlanInterval_DAY     PlanInterval = 1
	PlanInterval_WEEK    PlanInterval = 2
	PlanInterval_MONTH   PlanInterval = 3
	PlanInterval_YEAR    PlanInterval = 4
)

var PlanInterval_name = map[int32]string{
	0: "UNKNOWN",
	1: "DAY",
	2: "WEEK",
	3: "MONTH",
	4: "YEAR",
}

var PlanInterval_value = map[string]int32{
	"UNKNOWN": 0,
	"DAY":     1,
	"WEEK":    2,
	"MONTH":   3,
	"YEAR":    4,
}

func (x PlanInterval) String() string {
	return proto.EnumName(PlanInterval_name, int32(x))
}

func (PlanInterval) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{0}
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Active               bool     `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type CreateProductRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{1}
}

func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type CreateProductResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductResponse) Reset()         { *m = CreateProductResponse{} }
func (m *CreateProductResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductResponse) ProtoMessage()    {}
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{2}
}

func (m *CreateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductResponse.Unmarshal(m, b)
}
func (m *CreateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductResponse.Marshal(b, m, deterministic)
}
func (m *CreateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductResponse.Merge(m, src)
}
func (m *CreateProductResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductResponse.Size(m)
}
func (m *CreateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductResponse proto.InternalMessageInfo

type Plan struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount               int64        `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string       `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Interval             PlanInterval `protobuf:"varint,5,opt,name=interval,proto3,enum=go.micro.srv.provider.PlanInterval" json:"interval,omitempty"`
	ProductId            string       `protobuf:"bytes,6,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{3}
}

func (m *Plan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plan.Unmarshal(m, b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
}
func (m *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(m, src)
}
func (m *Plan) XXX_Size() int {
	return xxx_messageInfo_Plan.Size(m)
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func (m *Plan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plan) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Plan) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Plan) GetInterval() PlanInterval {
	if m != nil {
		return m.Interval
	}
	return PlanInterval_UNKNOWN
}

func (m *Plan) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type CreatePlanRequest struct {
	Plan                 *Plan    `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlanRequest) Reset()         { *m = CreatePlanRequest{} }
func (m *CreatePlanRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePlanRequest) ProtoMessage()    {}
func (*CreatePlanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{4}
}

func (m *CreatePlanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlanRequest.Unmarshal(m, b)
}
func (m *CreatePlanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlanRequest.Marshal(b, m, deterministic)
}
func (m *CreatePlanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlanRequest.Merge(m, src)
}
func (m *CreatePlanRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePlanRequest.Size(m)
}
func (m *CreatePlanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlanRequest proto.InternalMessageInfo

func (m *CreatePlanRequest) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

type CreatePlanResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlanResponse) Reset()         { *m = CreatePlanResponse{} }
func (m *CreatePlanResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePlanResponse) ProtoMessage()    {}
func (*CreatePlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{5}
}

func (m *CreatePlanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlanResponse.Unmarshal(m, b)
}
func (m *CreatePlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlanResponse.Marshal(b, m, deterministic)
}
func (m *CreatePlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlanResponse.Merge(m, src)
}
func (m *CreatePlanResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePlanResponse.Size(m)
}
func (m *CreatePlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlanResponse proto.InternalMessageInfo

type CreateCustomerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCustomerRequest) Reset()         { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()    {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{6}
}

func (m *CreateCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerRequest.Unmarshal(m, b)
}
func (m *CreateCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerRequest.Marshal(b, m, deterministic)
}
func (m *CreateCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerRequest.Merge(m, src)
}
func (m *CreateCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerRequest.Size(m)
}
func (m *CreateCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerRequest proto.InternalMessageInfo

type CreateCustomerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCustomerResponse) Reset()         { *m = CreateCustomerResponse{} }
func (m *CreateCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerResponse) ProtoMessage()    {}
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{7}
}

func (m *CreateCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerResponse.Unmarshal(m, b)
}
func (m *CreateCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerResponse.Marshal(b, m, deterministic)
}
func (m *CreateCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerResponse.Merge(m, src)
}
func (m *CreateCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerResponse.Size(m)
}
func (m *CreateCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerResponse proto.InternalMessageInfo

type CreateSubscriptionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubscriptionRequest) Reset()         { *m = CreateSubscriptionRequest{} }
func (m *CreateSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSubscriptionRequest) ProtoMessage()    {}
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{8}
}

func (m *CreateSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubscriptionRequest.Unmarshal(m, b)
}
func (m *CreateSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubscriptionRequest.Merge(m, src)
}
func (m *CreateSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSubscriptionRequest.Size(m)
}
func (m *CreateSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubscriptionRequest proto.InternalMessageInfo

type CreateSubscriptionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubscriptionResponse) Reset()         { *m = CreateSubscriptionResponse{} }
func (m *CreateSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSubscriptionResponse) ProtoMessage()    {}
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{9}
}

func (m *CreateSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubscriptionResponse.Unmarshal(m, b)
}
func (m *CreateSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *CreateSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubscriptionResponse.Merge(m, src)
}
func (m *CreateSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSubscriptionResponse.Size(m)
}
func (m *CreateSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubscriptionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("go.micro.srv.provider.PlanInterval", PlanInterval_name, PlanInterval_value)
	proto.RegisterType((*Product)(nil), "go.micro.srv.provider.Product")
	proto.RegisterType((*CreateProductRequest)(nil), "go.micro.srv.provider.CreateProductRequest")
	proto.RegisterType((*CreateProductResponse)(nil), "go.micro.srv.provider.CreateProductResponse")
	proto.RegisterType((*Plan)(nil), "go.micro.srv.provider.Plan")
	proto.RegisterType((*CreatePlanRequest)(nil), "go.micro.srv.provider.CreatePlanRequest")
	proto.RegisterType((*CreatePlanResponse)(nil), "go.micro.srv.provider.CreatePlanResponse")
	proto.RegisterType((*CreateCustomerRequest)(nil), "go.micro.srv.provider.CreateCustomerRequest")
	proto.RegisterType((*CreateCustomerResponse)(nil), "go.micro.srv.provider.CreateCustomerResponse")
	proto.RegisterType((*CreateSubscriptionRequest)(nil), "go.micro.srv.provider.CreateSubscriptionRequest")
	proto.RegisterType((*CreateSubscriptionResponse)(nil), "go.micro.srv.provider.CreateSubscriptionResponse")
}

func init() { proto.RegisterFile("provider/proto/provider.proto", fileDescriptor_8de96a1ce041752b) }

var fileDescriptor_8de96a1ce041752b = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x89, 0x9b, 0x38, 0x13, 0x88, 0xcc, 0xa8, 0x2d, 0xc6, 0xa5, 0x28, 0x32, 0x97, 0xf0,
	0xe5, 0x40, 0xb8, 0x70, 0x43, 0x55, 0x1a, 0x89, 0xaa, 0x22, 0x8d, 0x0c, 0xa8, 0xea, 0x09, 0x6d,
	0xed, 0x55, 0xb5, 0xc8, 0xde, 0x35, 0xeb, 0x75, 0xa4, 0xfe, 0x39, 0x2e, 0xfc, 0x31, 0xd4, 0xf5,
	0x3a, 0x4d, 0xa3, 0x34, 0x4a, 0x6f, 0x9e, 0x8f, 0x37, 0x33, 0xef, 0xbd, 0x95, 0xe1, 0x30, 0x97,
	0x62, 0xce, 0x12, 0x2a, 0x87, 0xb9, 0x14, 0x4a, 0x0c, 0xeb, 0x30, 0xd4, 0x21, 0xee, 0x5d, 0x89,
	0x30, 0x63, 0xb1, 0x14, 0x61, 0x21, 0xe7, 0x61, 0x5d, 0x0c, 0xae, 0xa0, 0x3d, 0x93, 0x22, 0x29,
	0x63, 0x85, 0x3d, 0x68, 0xb0, 0xc4, 0xb3, 0xfa, 0xd6, 0xa0, 0x13, 0x35, 0x58, 0x82, 0x08, 0x36,
	0x27, 0x19, 0xf5, 0x1a, 0x3a, 0xa3, 0xbf, 0xb1, 0x0f, 0xdd, 0x84, 0x16, 0xb1, 0x64, 0xb9, 0x62,
	0x82, 0x7b, 0x4d, 0x5d, 0x5a, 0x4e, 0xe1, 0x3e, 0xb4, 0x48, 0xac, 0xd8, 0x9c, 0x7a, 0x76, 0xdf,
	0x1a, 0x38, 0x91, 0x89, 0x82, 0x19, 0xec, 0x8e, 0x25, 0x25, 0x8a, 0x9a, 0x75, 0x11, 0xfd, 0x53,
	0xd2, 0x42, 0xe1, 0x67, 0x68, 0xe7, 0x55, 0x46, 0xaf, 0xee, 0x8e, 0x5e, 0x86, 0x6b, 0x2f, 0x0d,
	0x6b, 0x5c, 0xdd, 0x1e, 0x3c, 0x83, 0xbd, 0x95, 0x89, 0x45, 0x2e, 0x78, 0x41, 0x83, 0xbf, 0x16,
	0xd8, 0xb3, 0x94, 0xf0, 0xad, 0x18, 0xdd, 0xdc, 0x9b, 0x89, 0x92, 0x2b, 0x4d, 0xa6, 0x19, 0x99,
	0x08, 0x7d, 0x70, 0xe2, 0x52, 0x4a, 0xca, 0xe3, 0x6b, 0xcd, 0xa4, 0x13, 0x2d, 0x62, 0xfc, 0x02,
	0x0e, 0xe3, 0x8a, 0xca, 0x39, 0x49, 0xbd, 0x9d, 0xbe, 0x35, 0xe8, 0x8d, 0x5e, 0xdd, 0x77, 0x74,
	0x4a, 0xf8, 0x89, 0x69, 0x8d, 0x16, 0x20, 0x3c, 0x04, 0x30, 0x2c, 0x7e, 0xb1, 0xc4, 0x6b, 0xe9,
	0xf1, 0x1d, 0x93, 0x39, 0x49, 0x82, 0x63, 0x78, 0x6a, 0x98, 0xa5, 0x84, 0xd7, 0x42, 0x0d, 0xc1,
	0xce, 0x53, 0xc2, 0x8d, 0x4a, 0x07, 0x1b, 0x16, 0x46, 0xba, 0x31, 0xd8, 0x05, 0x5c, 0x9e, 0x62,
	0xc4, 0x59, 0xa8, 0x36, 0x2e, 0x0b, 0x25, 0x32, 0x2a, 0xcd, 0xfc, 0xc0, 0x83, 0xfd, 0xd5, 0x82,
	0x81, 0x1c, 0xc0, 0xf3, 0xaa, 0xf2, 0xbd, 0xbc, 0x5c, 0x18, 0x5d, 0xc3, 0x5e, 0x80, 0xbf, 0xae,
	0x58, 0x41, 0xdf, 0x8c, 0xe1, 0xf1, 0xb2, 0x04, 0xd8, 0x85, 0xf6, 0xcf, 0xe9, 0xe9, 0xf4, 0xec,
	0x7c, 0xea, 0x3e, 0xc2, 0x36, 0x34, 0x8f, 0x8f, 0x2e, 0x5c, 0x0b, 0x1d, 0xb0, 0xcf, 0x27, 0x93,
	0x53, 0xb7, 0x81, 0x1d, 0xd8, 0xf9, 0x76, 0x36, 0xfd, 0xf1, 0xd5, 0x6d, 0xde, 0x24, 0x2f, 0x26,
	0x47, 0x91, 0x6b, 0x8f, 0xfe, 0x35, 0xc1, 0x99, 0x19, 0x82, 0xf8, 0x1b, 0x9e, 0xdc, 0x71, 0x1d,
	0xdf, 0xde, 0xa3, 0xc4, 0xba, 0xd7, 0xe6, 0xbf, 0xdb, 0xae, 0xb9, 0xba, 0x1e, 0x09, 0xc0, 0xad,
	0x82, 0x38, 0xd8, 0x8c, 0xbd, 0xb5, 0xca, 0x7f, 0xbd, 0x45, 0xa7, 0x59, 0x91, 0x41, 0xef, 0xae,
	0xea, 0xb8, 0xf9, 0xc4, 0x15, 0xd7, 0xfc, 0xf7, 0x5b, 0x76, 0x9b, 0x75, 0xd7, 0xf5, 0x9b, 0x58,
	0x76, 0x0b, 0x3f, 0x6c, 0x1c, 0xb2, 0xc6, 0x75, 0xff, 0xe3, 0x03, 0x10, 0xd5, 0xea, 0xcb, 0x96,
	0xfe, 0x0f, 0x7d, 0xfa, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xed, 0x0f, 0x59, 0x3e, 0xa8, 0x04, 0x00,
	0x00,
}
