apiVersion: v1
kind: Service
metadata:
  name: kytra-srv-v1-push-notifications
  labels:
    app: kytra-srv-v1-push-notifications
    tier: srv
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: target-port
  selector:
    app: kytra-srv-v1-push-notifications
    tier: srv
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kytra-srv-v1-push-notifications
  labels:
    app: kytra-srv-v1-push-notifications
    tier: srv
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kytra-srv-v1-push-notifications
        tier: srv
    spec:
      serviceAccount: micro
      containers:
      - name: kytra-srv-v1-push-notifications
        image: eu.gcr.io/kytra-app/push-notifications-srv:0.1.1
        ports:
        - name: target-port
          containerPort: 8080
        env:
          - name: MICRO_REGISTRY
            value: kubernetes
          - name: MICRO_SELECTOR
            value: static
          - name: MICRO_SERVER_NAME
            value: kytra-srv-v1-push-notifications
          - name: MICRO_SERVER_ADDRESS
            value: 0.0.0.0:8080
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: push-notifications-srv
                key: dbHost
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: push-notifications-srv
                key: dbName
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: push-notifications-srv
                key: dbUser
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: push-notifications-srv
                key: dbPassword
