// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/v1api.proto

package v1api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for V1Api service

func NewV1ApiEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for V1Api service

type V1ApiService interface {
	Generate(ctx context.Context, in *GenerateRequest, opts ...client.CallOption) (*GenerateResponse, error)
}

type v1ApiService struct {
	c    client.Client
	name string
}

func NewV1ApiService(name string, c client.Client) V1ApiService {
	return &v1ApiService{
		c:    c,
		name: name,
	}
}

func (c *v1ApiService) Generate(ctx context.Context, in *GenerateRequest, opts ...client.CallOption) (*GenerateResponse, error) {
	req := c.c.NewRequest(c.name, "V1Api.Generate", in)
	out := new(GenerateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for V1Api service

type V1ApiHandler interface {
	Generate(context.Context, *GenerateRequest, *GenerateResponse) error
}

func RegisterV1ApiHandler(s server.Server, hdlr V1ApiHandler, opts ...server.HandlerOption) error {
	type v1Api interface {
		Generate(ctx context.Context, in *GenerateRequest, out *GenerateResponse) error
	}
	type V1Api struct {
		v1Api
	}
	h := &v1ApiHandler{hdlr}
	return s.Handle(s.NewHandler(&V1Api{h}, opts...))
}

type v1ApiHandler struct {
	V1ApiHandler
}

func (h *v1ApiHandler) Generate(ctx context.Context, in *GenerateRequest, out *GenerateResponse) error {
	return h.V1ApiHandler.Generate(ctx, in, out)
}
