apiVersion: v1
kind: Service
metadata:
  name: kytra-srv-v1-insights
  labels:
    app: kytra-srv-v1-insights
    tier: srv
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: target-port
  selector:
    app: kytra-srv-v1-insights
    tier: srv
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kytra-srv-v1-insights
  labels:
    app: kytra-srv-v1-insights
    tier: srv
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kytra-srv-v1-insights
        tier: srv
    spec:
      serviceAccount: micro
      containers:
      - name: kytra-srv-v1-insights
        image: eu.gcr.io/kytra-app/insights-srv:0.5.0
        ports:
        - name: target-port
          containerPort: 8080
        env:
          - name: MICRO_REGISTRY
            value: kubernetes
          - name: MICRO_SELECTOR
            value: static
          - name: MICRO_SERVER_NAME
            value: kytra-srv-v1-insights
          - name: MICRO_SERVER_ADDRESS
            value: 0.0.0.0:8080
          - name: MICRO_BROKER
            value: rabbitmq
          - name: MICRO_BROKER_ADDRESS
            valueFrom:
              secretKeyRef: 
                name: rabbitmq
                key: address
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: insights-srv
                key: dbHost
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: insights-srv
                key: dbName
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: insights-srv
                key: dbUser
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: insights-srv
                key: dbPassword
