// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/micro/services/dummy-one/proto/dummy-calle-1.proto

package dummy_calle_1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DummyOne service

type DummyOneService interface {
	Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type dummyOneService struct {
	c    client.Client
	name string
}

func NewDummyOneService(name string, c client.Client) DummyOneService {
	return &dummyOneService{
		c:    c,
		name: name,
	}
}

func (c *dummyOneService) Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "DummyOne.Hello", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DummyOne service

type DummyOneHandler interface {
	Hello(context.Context, *Request, *Response) error
}

func RegisterDummyOneHandler(s server.Server, hdlr DummyOneHandler, opts ...server.HandlerOption) error {
	type dummyOne interface {
		Hello(ctx context.Context, in *Request, out *Response) error
	}
	type DummyOne struct {
		dummyOne
	}
	h := &dummyOneHandler{hdlr}
	return s.Handle(s.NewHandler(&DummyOne{h}, opts...))
}

type dummyOneHandler struct {
	DummyOneHandler
}

func (h *dummyOneHandler) Hello(ctx context.Context, in *Request, out *Response) error {
	return h.DummyOneHandler.Hello(ctx, in, out)
}
