// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/apps/apps.proto

package go_micro_service_apps

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type App struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	RequiredRoles        []string `protobuf:"bytes,5,rep,name=required_roles,json=requiredRoles,proto3" json:"required_roles,omitempty"`
	Plans                []*Plan  `protobuf:"bytes,6,rep,name=plans,proto3" json:"plans,omitempty"`
	Active               bool     `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9f31522189aeee6, []int{0}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *App) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *App) GetRequiredRoles() []string {
	if m != nil {
		return m.RequiredRoles
	}
	return nil
}

func (m *App) GetPlans() []*Plan {
	if m != nil {
		return m.Plans
	}
	return nil
}

func (m *App) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type Plan struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Interval             string   `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9f31522189aeee6, []int{1}
}

func (m *Plan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plan.Unmarshal(m, b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
}
func (m *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(m, src)
}
func (m *Plan) XXX_Size() int {
	return xxx_messageInfo_Plan.Size(m)
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func (m *Plan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plan) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Plan) GetInterval() string {
	if m != nil {
		return m.Interval
	}
	return ""
}

type CreateRequest struct {
	App                  *App     `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9f31522189aeee6, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

type CreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9f31522189aeee6, []int{3}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

type ListRequest struct {
	OnlyActive           bool     `protobuf:"varint,1,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9f31522189aeee6, []int{4}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetOnlyActive() bool {
	if m != nil {
		return m.OnlyActive
	}
	return false
}

type ListResponse struct {
	Apps                 []*App   `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9f31522189aeee6, []int{5}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetApps() []*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

type ReadRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9f31522189aeee6, []int{6}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	App                  *App     `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9f31522189aeee6, []int{7}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

type UpdateRequest struct {
	App                  *App     `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9f31522189aeee6, []int{8}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

type UpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9f31522189aeee6, []int{9}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*App)(nil), "go.micro.service.apps.App")
	proto.RegisterType((*Plan)(nil), "go.micro.service.apps.Plan")
	proto.RegisterType((*CreateRequest)(nil), "go.micro.service.apps.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.service.apps.CreateResponse")
	proto.RegisterType((*ListRequest)(nil), "go.micro.service.apps.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "go.micro.service.apps.ListResponse")
	proto.RegisterType((*ReadRequest)(nil), "go.micro.service.apps.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "go.micro.service.apps.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "go.micro.service.apps.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "go.micro.service.apps.UpdateResponse")
}

func init() { proto.RegisterFile("proto/apps/apps.proto", fileDescriptor_d9f31522189aeee6) }

var fileDescriptor_d9f31522189aeee6 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x51, 0x8b, 0xd4, 0x30,
	0x10, 0xa6, 0xdb, 0x5e, 0xbd, 0x9b, 0xde, 0x2e, 0x12, 0x38, 0x29, 0x2b, 0x62, 0xa9, 0x1e, 0xec,
	0x83, 0x44, 0x5c, 0x5f, 0x3d, 0x61, 0xf1, 0x55, 0x50, 0x02, 0xfb, 0xea, 0x11, 0xdb, 0xe1, 0x08,
	0x74, 0x93, 0x5c, 0x92, 0x5d, 0xb8, 0x3f, 0x2a, 0xf8, 0x6f, 0x24, 0x49, 0x7b, 0x6e, 0xc5, 0x9e,
	0x8a, 0x2f, 0xcb, 0xce, 0x97, 0x6f, 0xbe, 0x99, 0xef, 0x1b, 0x28, 0x5c, 0x68, 0xa3, 0x9c, 0x7a,
	0xcd, 0xb5, 0xb6, 0xe1, 0x87, 0x86, 0x9a, 0x5c, 0xdc, 0x28, 0xba, 0x13, 0x8d, 0x51, 0xd4, 0xa2,
	0x39, 0x88, 0x06, 0xa9, 0x7f, 0xac, 0xbf, 0x27, 0x90, 0x6e, 0xb4, 0x26, 0x0b, 0x98, 0x89, 0xb6,
	0x4c, 0xaa, 0x64, 0x75, 0xc6, 0x66, 0xa2, 0x25, 0x04, 0x32, 0xc9, 0x77, 0x58, 0xce, 0x02, 0x12,
	0xfe, 0x93, 0x25, 0x9c, 0x36, 0xdc, 0xe1, 0x8d, 0x32, 0x77, 0x65, 0x1a, 0xf0, 0xfb, 0x9a, 0x54,
	0x50, 0xb4, 0x68, 0x1b, 0x23, 0xb4, 0x13, 0x4a, 0x96, 0x59, 0x78, 0x3e, 0x86, 0xc8, 0x25, 0x2c,
	0x0c, 0xde, 0xee, 0x85, 0xc1, 0xf6, 0xda, 0xa8, 0x0e, 0x6d, 0x79, 0x52, 0xa5, 0xab, 0x33, 0x36,
	0x1f, 0x50, 0xe6, 0x41, 0xf2, 0x06, 0x4e, 0x74, 0xc7, 0xa5, 0x2d, 0xf3, 0x2a, 0x5d, 0x15, 0xeb,
	0xa7, 0xf4, 0xb7, 0x7b, 0xd3, 0xcf, 0x1d, 0x97, 0x2c, 0x32, 0xc9, 0x13, 0xc8, 0x79, 0xe3, 0xc4,
	0x01, 0xcb, 0x47, 0x55, 0xb2, 0x3a, 0x65, 0x7d, 0x55, 0x7f, 0x81, 0xcc, 0xd3, 0xfe, 0xca, 0x9b,
	0xd7, 0xd8, 0xa9, 0xbd, 0x74, 0xc1, 0x59, 0xca, 0xfa, 0xca, 0x7b, 0x16, 0xd2, 0xa1, 0x39, 0xf0,
	0xae, 0x37, 0x75, 0x5f, 0xd7, 0x57, 0x30, 0xff, 0x60, 0x90, 0x3b, 0x64, 0x78, 0xbb, 0x47, 0xeb,
	0xc8, 0x2b, 0x48, 0xb9, 0xd6, 0x61, 0x52, 0xb1, 0x5e, 0x4e, 0x6c, 0xbe, 0xd1, 0x9a, 0x79, 0x5a,
	0xfd, 0x18, 0x16, 0x43, 0xbb, 0xd5, 0x4a, 0x5a, 0xac, 0x29, 0x14, 0x1f, 0x85, 0x75, 0x83, 0xdc,
	0x73, 0x28, 0x94, 0xec, 0xee, 0xae, 0x7b, 0x73, 0x49, 0x30, 0x07, 0x1e, 0xda, 0x44, 0x83, 0xef,
	0xe1, 0x3c, 0xf2, 0x63, 0x3f, 0xa1, 0x90, 0xf9, 0x11, 0x65, 0x12, 0xa2, 0x7b, 0x68, 0x81, 0xc0,
	0xab, 0x9f, 0x41, 0xc1, 0x90, 0xb7, 0xc3, 0xbc, 0x5f, 0x72, 0xaa, 0xdf, 0xc1, 0x79, 0x7c, 0xee,
	0xe5, 0xff, 0xcd, 0xde, 0x15, 0xcc, 0xb7, 0xba, 0xfd, 0x9f, 0x74, 0x86, 0xf6, 0x38, 0x7e, 0xfd,
	0x6d, 0x06, 0xd9, 0x46, 0x6b, 0x4b, 0xb6, 0x90, 0xc7, 0xe0, 0xc8, 0xcb, 0x09, 0x95, 0xd1, 0x59,
	0x96, 0x97, 0x7f, 0x60, 0xf5, 0xf6, 0x3e, 0x41, 0xe6, 0xd3, 0x24, 0xf5, 0x04, 0xfd, 0xe8, 0x34,
	0xcb, 0x17, 0x0f, 0x72, 0x7e, 0x0a, 0xfa, 0xfc, 0x26, 0x05, 0x8f, 0xb2, 0x9f, 0x14, 0x1c, 0x1d,
	0x60, 0x0b, 0x79, 0xcc, 0x64, 0xd2, 0xf8, 0x28, 0xf1, 0x49, 0xe3, 0xe3, 0x60, 0xbf, 0xe6, 0xe1,
	0x0b, 0xf1, 0xf6, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x34, 0x65, 0xfc, 0x3a, 0x04, 0x00,
	0x00,
}
