// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/subscription.proto

package subscription

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v3/api"
	client "github.com/micro/go-micro/v3/client"
	server "github.com/micro/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SubscriptionService service

func NewSubscriptionServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SubscriptionService service

type SubscriptionService interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Cancel(ctx context.Context, in *CancelRequest, opts ...client.CallOption) (*CancelResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
}

type subscriptionService struct {
	c    client.Client
	name string
}

func NewSubscriptionService(name string, c client.Client) SubscriptionService {
	return &subscriptionService{
		c:    c,
		name: name,
	}
}

func (c *subscriptionService) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.name, "SubscriptionService.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionService) Cancel(ctx context.Context, in *CancelRequest, opts ...client.CallOption) (*CancelResponse, error) {
	req := c.c.NewRequest(c.name, "SubscriptionService.Cancel", in)
	out := new(CancelResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "SubscriptionService.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SubscriptionService service

type SubscriptionServiceHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Cancel(context.Context, *CancelRequest, *CancelResponse) error
	List(context.Context, *ListRequest, *ListResponse) error
}

func RegisterSubscriptionServiceHandler(s server.Server, hdlr SubscriptionServiceHandler, opts ...server.HandlerOption) error {
	type subscriptionService interface {
		Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error
		Cancel(ctx context.Context, in *CancelRequest, out *CancelResponse) error
		List(ctx context.Context, in *ListRequest, out *ListResponse) error
	}
	type SubscriptionService struct {
		subscriptionService
	}
	h := &subscriptionServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SubscriptionService{h}, opts...))
}

type subscriptionServiceHandler struct {
	SubscriptionServiceHandler
}

func (h *subscriptionServiceHandler) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.SubscriptionServiceHandler.Create(ctx, in, out)
}

func (h *subscriptionServiceHandler) Cancel(ctx context.Context, in *CancelRequest, out *CancelResponse) error {
	return h.SubscriptionServiceHandler.Cancel(ctx, in, out)
}

func (h *subscriptionServiceHandler) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.SubscriptionServiceHandler.List(ctx, in, out)
}
