apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-srv
imagePullSecrets:
- name: regcred
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-srv
  namespace: micro
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - namespaces
  - serviceaccounts
  verbs:
  - create
  - delete
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-srv
  namespace: micro
subjects:
- kind: ServiceAccount
  name: platform-srv
  namespace: micro
roleRef:
  kind: ClusterRole
  name: platform-srv
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-srv
  namespace: micro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-srv
subjects:
- kind: ServiceAccount
  name: platform-srv
