// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/micro/micro/v3/service/client"

	m3o_alert "github.com/m3o/services/alert/proto/alert"

	mock "github.com/stretchr/testify/mock"
)

// AlertService is an autogenerated mock type for the AlertService type
type AlertService struct {
	mock.Mock
}

// ReportEvent provides a mock function with given fields: ctx, in, opts
func (_m *AlertService) ReportEvent(ctx context.Context, in *m3o_alert.ReportEventRequest, opts ...client.CallOption) (*m3o_alert.ReportEventResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *m3o_alert.ReportEventResponse
	if rf, ok := ret.Get(0).(func(context.Context, *m3o_alert.ReportEventRequest, ...client.CallOption) *m3o_alert.ReportEventResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*m3o_alert.ReportEventResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *m3o_alert.ReportEventRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
