apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-service-latest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      micro: service
      name: kubernetes-service
      version: latest
  template:
    metadata:
      labels:
        micro: service
        name: kubernetes-service
        version: latest
    spec:
      containers:
      - env:
        - name: GO111MODULE
          value: "on"
        - name: MICRO_AUTH_ADDRESS
          value: micro-auth:8010
        - name: MICRO_NETWORK_ADDRESS
          value: micro-network:8080
        - name: MICRO_ROUTER_ADDRESS
          value: micro-runtime:8084
        - name: GOPROXY
          value: http://athens-proxy
        - name: MICRO_REGISTRY_ADDRESS
          value: micro-registry:8000
        - name: MICRO_STORE_ADDRESS
          value: micro-store:8002
        - name: MICRO_BROKER
          value: service
        - name: MICRO_NETWORK
          value: service
        - name: MICRO_ROUTER
          value: service
        - name: MICRO_STORE
          value: service
        - name: MICRO_BROKER_ADDRESS
          value: micro-store:8001
        - name: MICRO_CONFIG
          value: service
        - name: MICRO_RUNTIME_ADDRESS
          value: micro-runtime:8088
        - name: MICRO_AUTH
          value: service
        - name: MICRO_REGISTRY
          value: service
        - name: MICRO_RUNTIME
          value: service
        - name: MICRO_LOG_LEVEL
          value: trace
        image: docker.pkg.github.com/micro/services/kubernetes-service
        imagePullPolicy: Always
        name: kubernetes-service
        ports:
        - containerPort: 8080
          name: service-port
          protocol: TCP
      serviceAccount: kubernetes-srv
      serviceAccountName: kubernetes-srv