apiVersion: v1
kind: Pod
metadata:
  name: kytra-srv-v1-stock-colors
spec:
  containers:
  - name: kytra-srv-v1-stock-colors
    image: eu.gcr.io/kytra-app/stock-colors:0.1.3
    env:
    - name: IEX_TOKEN
      valueFrom:
        secretKeyRef:
          name: iex
          key: token
    - name: PHOTOS_ADDRESS
      valueFrom:
        secretKeyRef:
          name: photos
          key: address
    - name: MICRO_REGISTRY
      value: kubernetes
    - name: MICRO_SELECTOR
      value: static
    - name: MICRO_SERVER_NAME
      value: kytra-srv-v1-stock-colors
    - name: MICRO_SERVER_ADDRESS
      value: 0.0.0.0:8080
    ports:
    - name: target-port
      containerPort: 8080
