// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/micro/services/dummy-two/proto/dummy-calle-2.proto

package dummy_calle_2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DummyTwo service

type DummyTwoService interface {
	Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type dummyTwoService struct {
	c    client.Client
	name string
}

func NewDummyTwoService(name string, c client.Client) DummyTwoService {
	return &dummyTwoService{
		c:    c,
		name: name,
	}
}

func (c *dummyTwoService) Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "DummyTwo.Hello", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DummyTwo service

type DummyTwoHandler interface {
	Hello(context.Context, *Request, *Response) error
}

func RegisterDummyTwoHandler(s server.Server, hdlr DummyTwoHandler, opts ...server.HandlerOption) error {
	type dummyTwo interface {
		Hello(ctx context.Context, in *Request, out *Response) error
	}
	type DummyTwo struct {
		dummyTwo
	}
	h := &dummyTwoHandler{hdlr}
	return s.Handle(s.NewHandler(&DummyTwo{h}, opts...))
}

type dummyTwoHandler struct {
	DummyTwoHandler
}

func (h *dummyTwoHandler) Hello(ctx context.Context, in *Request, out *Response) error {
	return h.DummyTwoHandler.Hello(ctx, in, out)
}
