apiVersion: v1
kind: Service
metadata:
  name: kytra-api-v2-charts
  labels:
    app: kytra-api-v2-charts
    tier: api
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: target-port
  selector:
    app: kytra-api-v2-charts
    tier: api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kytra-api-v2-charts
  labels:
    app: kytra-api-v2-charts
    tier: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kytra-api-v2-charts
        tier: api
    spec:
      serviceAccount: micro
      containers:
      - name: kytra-api-v2-charts
        image: eu.gcr.io/kytra-app/charts-api-v2:0.2.2
        ports:
        - name: target-port
          containerPort: 8080
        env:
          - name: MICRO_REGISTRY
            value: kubernetes
          - name: MICRO_SELECTOR
            value: static
          - name: MICRO_SERVER_NAME
            value: kytra-api-v2-charts
          - name: MICRO_SERVER_ADDRESS
            value: 0.0.0.0:8080
          - name: IEX_TOKEN
            valueFrom:
              secretKeyRef:
                name: iex
                key: token
          - name: JWT_SIGNING_KEY
            valueFrom:
              secretKeyRef:
                name: auth
                key: jwtSigningKey
      
