// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/importer/importer.proto

package go_micro_api_apps_importer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Importer service

type ImporterService interface {
	Import(ctx context.Context, in *ImportRequest, opts ...client.CallOption) (*ImportResponse, error)
}

type importerService struct {
	c    client.Client
	name string
}

func NewImporterService(name string, c client.Client) ImporterService {
	return &importerService{
		c:    c,
		name: name,
	}
}

func (c *importerService) Import(ctx context.Context, in *ImportRequest, opts ...client.CallOption) (*ImportResponse, error) {
	req := c.c.NewRequest(c.name, "Importer.Import", in)
	out := new(ImportResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Importer service

type ImporterHandler interface {
	Import(context.Context, *ImportRequest, *ImportResponse) error
}

func RegisterImporterHandler(s server.Server, hdlr ImporterHandler, opts ...server.HandlerOption) error {
	type importer interface {
		Import(ctx context.Context, in *ImportRequest, out *ImportResponse) error
	}
	type Importer struct {
		importer
	}
	h := &importerHandler{hdlr}
	return s.Handle(s.NewHandler(&Importer{h}, opts...))
}

type importerHandler struct {
	ImporterHandler
}

func (h *importerHandler) Import(ctx context.Context, in *ImportRequest, out *ImportResponse) error {
	return h.ImporterHandler.Import(ctx, in, out)
}
