// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/services/projects/enviroments/proto/enviroments.proto

package go_micro_service_projects_enviroments

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Enviroment struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ProjectId            string   `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Enviroment) Reset()         { *m = Enviroment{} }
func (m *Enviroment) String() string { return proto.CompactTextString(m) }
func (*Enviroment) ProtoMessage()    {}
func (*Enviroment) Descriptor() ([]byte, []int) {
	return fileDescriptor_298e4b7013169529, []int{0}
}

func (m *Enviroment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Enviroment.Unmarshal(m, b)
}
func (m *Enviroment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Enviroment.Marshal(b, m, deterministic)
}
func (m *Enviroment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Enviroment.Merge(m, src)
}
func (m *Enviroment) XXX_Size() int {
	return xxx_messageInfo_Enviroment.Size(m)
}
func (m *Enviroment) XXX_DiscardUnknown() {
	xxx_messageInfo_Enviroment.DiscardUnknown(m)
}

var xxx_messageInfo_Enviroment proto.InternalMessageInfo

func (m *Enviroment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Enviroment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Enviroment) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Enviroment) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Enviroment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateRequest struct {
	Enviroment           *Enviroment `protobuf:"bytes,1,opt,name=enviroment,proto3" json:"enviroment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_298e4b7013169529, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetEnviroment() *Enviroment {
	if m != nil {
		return m.Enviroment
	}
	return nil
}

type CreateResponse struct {
	Enviroment           *Enviroment `protobuf:"bytes,1,opt,name=enviroment,proto3" json:"enviroment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_298e4b7013169529, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetEnviroment() *Enviroment {
	if m != nil {
		return m.Enviroment
	}
	return nil
}

type ReadRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ProjectId            string   `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_298e4b7013169529, []int{3}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ReadRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type ReadResponse struct {
	Enviroment           *Enviroment   `protobuf:"bytes,1,opt,name=enviroment,proto3" json:"enviroment,omitempty"`
	Enviroments          []*Enviroment `protobuf:"bytes,2,rep,name=enviroments,proto3" json:"enviroments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_298e4b7013169529, []int{4}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetEnviroment() *Enviroment {
	if m != nil {
		return m.Enviroment
	}
	return nil
}

func (m *ReadResponse) GetEnviroments() []*Enviroment {
	if m != nil {
		return m.Enviroments
	}
	return nil
}

type UpdateRequest struct {
	Enviroment           *Enviroment `protobuf:"bytes,1,opt,name=enviroment,proto3" json:"enviroment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_298e4b7013169529, []int{5}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetEnviroment() *Enviroment {
	if m != nil {
		return m.Enviroment
	}
	return nil
}

type UpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_298e4b7013169529, []int{6}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_298e4b7013169529, []int{7}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_298e4b7013169529, []int{8}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Enviroment)(nil), "go.micro.service.projects.enviroments.Enviroment")
	proto.RegisterType((*CreateRequest)(nil), "go.micro.service.projects.enviroments.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.service.projects.enviroments.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "go.micro.service.projects.enviroments.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "go.micro.service.projects.enviroments.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "go.micro.service.projects.enviroments.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "go.micro.service.projects.enviroments.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.service.projects.enviroments.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.service.projects.enviroments.DeleteResponse")
}

func init() {
	proto.RegisterFile("github.com/micro/services/projects/enviroments/proto/enviroments.proto", fileDescriptor_298e4b7013169529)
}

var fileDescriptor_298e4b7013169529 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0x4e, 0x83, 0x40,
	0x10, 0x2e, 0x50, 0x9b, 0x74, 0xb0, 0x8d, 0xd9, 0x13, 0x69, 0x34, 0x36, 0x24, 0x26, 0x9e, 0x96,
	0xd8, 0xea, 0x13, 0xf8, 0x93, 0x78, 0x14, 0xe3, 0xc5, 0x8b, 0xa1, 0x30, 0xa9, 0x6b, 0x84, 0xa5,
	0x2c, 0x6d, 0x1f, 0xc3, 0xb7, 0xf1, 0xa5, 0x7c, 0x09, 0xc3, 0x02, 0x65, 0xe1, 0x60, 0xb6, 0x26,
	0x3d, 0x01, 0xdf, 0xee, 0x37, 0xdf, 0xcc, 0xf7, 0x4d, 0x80, 0x87, 0x25, 0xcb, 0xdf, 0xd7, 0x0b,
	0x1a, 0xf2, 0xd8, 0x8b, 0x59, 0x98, 0x71, 0x4f, 0x60, 0xb6, 0x61, 0x21, 0x0a, 0x2f, 0xcd, 0xf8,
	0x07, 0x86, 0xb9, 0xf0, 0x30, 0xd9, 0xb0, 0x8c, 0xc7, 0x98, 0xe4, 0x12, 0xcc, 0xb9, 0x8a, 0x50,
	0x89, 0x90, 0x8b, 0x25, 0xa7, 0x92, 0x4f, 0x2b, 0x3e, 0xad, 0xe9, 0x54, 0xb9, 0xec, 0x7e, 0x19,
	0x00, 0xf7, 0xbb, 0x6f, 0x32, 0x06, 0x93, 0x45, 0x8e, 0x31, 0x35, 0x2e, 0x87, 0xbe, 0xc9, 0x22,
	0x42, 0xa0, 0x9f, 0x04, 0x31, 0x3a, 0xa6, 0x44, 0xe4, 0x3b, 0x39, 0x85, 0x61, 0xf1, 0x14, 0x69,
	0x10, 0xa2, 0x63, 0xc9, 0x83, 0x06, 0x20, 0x67, 0x00, 0x95, 0xd0, 0x1b, 0x8b, 0x9c, 0x7e, 0x79,
	0x5c, 0x21, 0x8f, 0x11, 0x99, 0x82, 0x1d, 0xa1, 0x08, 0x33, 0x96, 0xe6, 0x8c, 0x27, 0xce, 0x91,
	0x3c, 0x57, 0x21, 0x77, 0x01, 0xa3, 0xdb, 0x0c, 0x83, 0x1c, 0x7d, 0x5c, 0xad, 0x51, 0xe4, 0xe4,
	0x09, 0xa0, 0xe9, 0x58, 0xf6, 0x66, 0xcf, 0xae, 0xa8, 0xd6, 0x78, 0xb4, 0x19, 0xcd, 0x57, 0x8a,
	0xb8, 0x21, 0x8c, 0x6b, 0x0d, 0x91, 0xf2, 0x44, 0xe0, 0x21, 0x44, 0x5e, 0xc1, 0xf6, 0x31, 0x88,
	0xea, 0x31, 0xba, 0xd6, 0xb6, 0x6c, 0x34, 0xff, 0xb6, 0xd1, 0xea, 0xd8, 0xe8, 0x7e, 0x1b, 0x70,
	0x5c, 0x16, 0x3f, 0x58, 0xff, 0xe4, 0x19, 0x6c, 0xe5, 0x96, 0x63, 0x4e, 0xad, 0xff, 0xd5, 0x54,
	0xab, 0x14, 0xe9, 0xbe, 0xa4, 0xd1, 0x61, 0xd3, 0x3d, 0x81, 0x71, 0xad, 0x51, 0xba, 0xe3, 0x9e,
	0xc3, 0xe8, 0x0e, 0x3f, 0xb1, 0x51, 0xed, 0x84, 0x51, 0x50, 0xea, 0x0b, 0x25, 0x65, 0xf6, 0x63,
	0x81, 0xdd, 0xd4, 0x17, 0x64, 0x0b, 0x83, 0x72, 0x65, 0xc8, 0xb5, 0x66, 0x77, 0xad, 0x2d, 0x9e,
	0xdc, 0xec, 0xc9, 0xaa, 0x3a, 0xef, 0x91, 0x15, 0xf4, 0x8b, 0xa4, 0xc9, 0x4c, 0xb3, 0x80, 0xb2,
	0x73, 0x93, 0xf9, 0x5e, 0x9c, 0x9d, 0xe4, 0x16, 0x06, 0xa5, 0x81, 0xda, 0xb3, 0xb6, 0x32, 0xd5,
	0x9e, 0xb5, 0x93, 0x92, 0x14, 0x2e, 0x63, 0xd0, 0x16, 0x6e, 0xc5, 0xaa, 0x2d, 0xdc, 0xce, 0xda,
	0xed, 0x2d, 0x06, 0xf2, 0xa7, 0x39, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x8e, 0xb2, 0xb3,
	0x7e, 0x05, 0x00, 0x00,
}
