// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/micro/services/projects/enviroments/proto/enviroments.proto

package go_micro_service_projects_enviroments

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Enviroments service

func NewEnviromentsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Enviroments service

type EnviromentsService interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
}

type enviromentsService struct {
	c    client.Client
	name string
}

func NewEnviromentsService(name string, c client.Client) EnviromentsService {
	return &enviromentsService{
		c:    c,
		name: name,
	}
}

func (c *enviromentsService) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.name, "Enviroments.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enviromentsService) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.name, "Enviroments.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enviromentsService) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.name, "Enviroments.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enviromentsService) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.name, "Enviroments.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Enviroments service

type EnviromentsHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
}

func RegisterEnviromentsHandler(s server.Server, hdlr EnviromentsHandler, opts ...server.HandlerOption) error {
	type enviroments interface {
		Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error
		Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error
		Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error
		Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error
	}
	type Enviroments struct {
		enviroments
	}
	h := &enviromentsHandler{hdlr}
	return s.Handle(s.NewHandler(&Enviroments{h}, opts...))
}

type enviromentsHandler struct {
	EnviromentsHandler
}

func (h *enviromentsHandler) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.EnviromentsHandler.Create(ctx, in, out)
}

func (h *enviromentsHandler) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.EnviromentsHandler.Read(ctx, in, out)
}

func (h *enviromentsHandler) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.EnviromentsHandler.Update(ctx, in, out)
}

func (h *enviromentsHandler) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.EnviromentsHandler.Delete(ctx, in, out)
}
