// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account/account.proto

package go_micro_api_account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Subscription struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{0}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

type User struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64            `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64            `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	FirstName            string           `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string           `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string           `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Username             string           `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	PaymentMethods       []*PaymentMethod `protobuf:"bytes,8,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	Subscriptions        []*Subscription  `protobuf:"bytes,9,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *User) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPaymentMethods() []*PaymentMethod {
	if m != nil {
		return m.PaymentMethods
	}
	return nil
}

func (m *User) GetSubscriptions() []*Subscription {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type ReadUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserRequest) Reset()         { *m = ReadUserRequest{} }
func (m *ReadUserRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUserRequest) ProtoMessage()    {}
func (*ReadUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{2}
}

func (m *ReadUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserRequest.Unmarshal(m, b)
}
func (m *ReadUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserRequest.Marshal(b, m, deterministic)
}
func (m *ReadUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserRequest.Merge(m, src)
}
func (m *ReadUserRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUserRequest.Size(m)
}
func (m *ReadUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserRequest proto.InternalMessageInfo

type ReadUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserResponse) Reset()         { *m = ReadUserResponse{} }
func (m *ReadUserResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUserResponse) ProtoMessage()    {}
func (*ReadUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{3}
}

func (m *ReadUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserResponse.Unmarshal(m, b)
}
func (m *ReadUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserResponse.Marshal(b, m, deterministic)
}
func (m *ReadUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserResponse.Merge(m, src)
}
func (m *ReadUserResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUserResponse.Size(m)
}
func (m *ReadUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserResponse proto.InternalMessageInfo

func (m *ReadUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{4}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{5}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{6}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

type DeleteUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{7}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

type PaymentMethod struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	CardBrand            string   `protobuf:"bytes,5,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	CardExpMonth         string   `protobuf:"bytes,6,opt,name=card_exp_month,json=cardExpMonth,proto3" json:"card_exp_month,omitempty"`
	CardExpYear          string   `protobuf:"bytes,7,opt,name=card_exp_year,json=cardExpYear,proto3" json:"card_exp_year,omitempty"`
	CardLast_4           string   `protobuf:"bytes,8,opt,name=card_last_4,json=cardLast4,proto3" json:"card_last_4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentMethod) Reset()         { *m = PaymentMethod{} }
func (m *PaymentMethod) String() string { return proto.CompactTextString(m) }
func (*PaymentMethod) ProtoMessage()    {}
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{8}
}

func (m *PaymentMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethod.Unmarshal(m, b)
}
func (m *PaymentMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethod.Marshal(b, m, deterministic)
}
func (m *PaymentMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethod.Merge(m, src)
}
func (m *PaymentMethod) XXX_Size() int {
	return xxx_messageInfo_PaymentMethod.Size(m)
}
func (m *PaymentMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethod.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethod proto.InternalMessageInfo

func (m *PaymentMethod) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentMethod) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *PaymentMethod) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PaymentMethod) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PaymentMethod) GetCardBrand() string {
	if m != nil {
		return m.CardBrand
	}
	return ""
}

func (m *PaymentMethod) GetCardExpMonth() string {
	if m != nil {
		return m.CardExpMonth
	}
	return ""
}

func (m *PaymentMethod) GetCardExpYear() string {
	if m != nil {
		return m.CardExpYear
	}
	return ""
}

func (m *PaymentMethod) GetCardLast_4() string {
	if m != nil {
		return m.CardLast_4
	}
	return ""
}

type CreatePaymentMethodRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePaymentMethodRequest) Reset()         { *m = CreatePaymentMethodRequest{} }
func (m *CreatePaymentMethodRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentMethodRequest) ProtoMessage()    {}
func (*CreatePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{9}
}

func (m *CreatePaymentMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentMethodRequest.Unmarshal(m, b)
}
func (m *CreatePaymentMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentMethodRequest.Marshal(b, m, deterministic)
}
func (m *CreatePaymentMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentMethodRequest.Merge(m, src)
}
func (m *CreatePaymentMethodRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentMethodRequest.Size(m)
}
func (m *CreatePaymentMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentMethodRequest proto.InternalMessageInfo

func (m *CreatePaymentMethodRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePaymentMethodRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePaymentMethodRequest) Reset()         { *m = DeletePaymentMethodRequest{} }
func (m *DeletePaymentMethodRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePaymentMethodRequest) ProtoMessage()    {}
func (*DeletePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{10}
}

func (m *DeletePaymentMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePaymentMethodRequest.Unmarshal(m, b)
}
func (m *DeletePaymentMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePaymentMethodRequest.Marshal(b, m, deterministic)
}
func (m *DeletePaymentMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePaymentMethodRequest.Merge(m, src)
}
func (m *DeletePaymentMethodRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePaymentMethodRequest.Size(m)
}
func (m *DeletePaymentMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePaymentMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePaymentMethodRequest proto.InternalMessageInfo

func (m *DeletePaymentMethodRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreatePaymentMethodResponse struct {
	PaymentMethod        *PaymentMethod `protobuf:"bytes,1,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreatePaymentMethodResponse) Reset()         { *m = CreatePaymentMethodResponse{} }
func (m *CreatePaymentMethodResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentMethodResponse) ProtoMessage()    {}
func (*CreatePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{11}
}

func (m *CreatePaymentMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentMethodResponse.Unmarshal(m, b)
}
func (m *CreatePaymentMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentMethodResponse.Marshal(b, m, deterministic)
}
func (m *CreatePaymentMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentMethodResponse.Merge(m, src)
}
func (m *CreatePaymentMethodResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentMethodResponse.Size(m)
}
func (m *CreatePaymentMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentMethodResponse proto.InternalMessageInfo

func (m *CreatePaymentMethodResponse) GetPaymentMethod() *PaymentMethod {
	if m != nil {
		return m.PaymentMethod
	}
	return nil
}

type DeletePaymentMethodResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePaymentMethodResponse) Reset()         { *m = DeletePaymentMethodResponse{} }
func (m *DeletePaymentMethodResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePaymentMethodResponse) ProtoMessage()    {}
func (*DeletePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{12}
}

func (m *DeletePaymentMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePaymentMethodResponse.Unmarshal(m, b)
}
func (m *DeletePaymentMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePaymentMethodResponse.Marshal(b, m, deterministic)
}
func (m *DeletePaymentMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePaymentMethodResponse.Merge(m, src)
}
func (m *DeletePaymentMethodResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePaymentMethodResponse.Size(m)
}
func (m *DeletePaymentMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePaymentMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePaymentMethodResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Subscription)(nil), "go.micro.api.account.Subscription")
	proto.RegisterType((*User)(nil), "go.micro.api.account.User")
	proto.RegisterType((*ReadUserRequest)(nil), "go.micro.api.account.ReadUserRequest")
	proto.RegisterType((*ReadUserResponse)(nil), "go.micro.api.account.ReadUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "go.micro.api.account.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "go.micro.api.account.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "go.micro.api.account.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "go.micro.api.account.DeleteUserResponse")
	proto.RegisterType((*PaymentMethod)(nil), "go.micro.api.account.PaymentMethod")
	proto.RegisterType((*CreatePaymentMethodRequest)(nil), "go.micro.api.account.CreatePaymentMethodRequest")
	proto.RegisterType((*DeletePaymentMethodRequest)(nil), "go.micro.api.account.DeletePaymentMethodRequest")
	proto.RegisterType((*CreatePaymentMethodResponse)(nil), "go.micro.api.account.CreatePaymentMethodResponse")
	proto.RegisterType((*DeletePaymentMethodResponse)(nil), "go.micro.api.account.DeletePaymentMethodResponse")
}

func init() { proto.RegisterFile("proto/account/account.proto", fileDescriptor_5d492a0187472a3b) }

var fileDescriptor_5d492a0187472a3b = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0x5d, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x9b, 0x34, 0x6d, 0xe2, 0x49, 0x93, 0x92, 0x49, 0x24, 0x2c, 0x47, 0x45, 0x91, 0xf9,
	0xca, 0x03, 0x32, 0x10, 0x7a, 0x01, 0xda, 0x22, 0x01, 0x6a, 0x11, 0x32, 0xea, 0x03, 0xe2, 0xc1,
	0xda, 0xd8, 0x0b, 0xb5, 0x14, 0x7f, 0xb0, 0xbb, 0x91, 0x9a, 0x9e, 0x87, 0x03, 0x71, 0x13, 0xae,
	0x80, 0x76, 0xbd, 0x26, 0x76, 0xb0, 0x69, 0xc3, 0x53, 0x32, 0x1f, 0x3b, 0xff, 0xdd, 0x99, 0xdf,
	0xc8, 0x30, 0x4e, 0x59, 0x22, 0x92, 0xe7, 0xc4, 0xf7, 0x93, 0x65, 0x2c, 0xf2, 0x5f, 0x47, 0x79,
	0x71, 0xf4, 0x2d, 0x71, 0xa2, 0xd0, 0x67, 0x89, 0x43, 0xd2, 0xd0, 0xd1, 0x31, 0xbb, 0x0f, 0x07,
	0x9f, 0x96, 0x73, 0xee, 0xb3, 0x30, 0x15, 0x61, 0x12, 0xdb, 0x3f, 0x9b, 0xd0, 0xba, 0xe4, 0x94,
	0x61, 0x1f, 0x9a, 0x61, 0x60, 0x36, 0x26, 0x8d, 0xa9, 0xe1, 0x36, 0xc3, 0x00, 0x4d, 0x68, 0xfb,
	0x8c, 0x12, 0x41, 0x03, 0xb3, 0x39, 0x69, 0x4c, 0x77, 0xdd, 0xdc, 0x94, 0x91, 0x65, 0x1a, 0xa8,
	0xc8, 0x6e, 0x16, 0xd1, 0x26, 0x1e, 0x01, 0x7c, 0x0d, 0x19, 0x17, 0x5e, 0x4c, 0x22, 0x6a, 0xb6,
	0x54, 0x2d, 0x43, 0x79, 0x3e, 0x90, 0x88, 0xe2, 0x18, 0x8c, 0x05, 0xc9, 0xa3, 0x7b, 0x2a, 0xda,
	0x91, 0x0e, 0x15, 0x1c, 0xc1, 0x1e, 0x8d, 0x48, 0xb8, 0x30, 0xf7, 0x55, 0x20, 0x33, 0xd0, 0x82,
	0xce, 0x92, 0x53, 0xa6, 0x4e, 0xb4, 0xb3, 0x13, 0xb9, 0x8d, 0xe7, 0x70, 0x98, 0x92, 0x55, 0x44,
	0x63, 0xe1, 0x45, 0x54, 0x5c, 0x25, 0x01, 0x37, 0x3b, 0x93, 0xdd, 0x69, 0x77, 0xf6, 0xd0, 0xa9,
	0x7a, 0xba, 0xf3, 0x31, 0x4b, 0xbe, 0x50, 0xb9, 0x6e, 0x3f, 0x2d, 0x9a, 0x1c, 0xdf, 0x42, 0x8f,
	0x17, 0x1a, 0xc3, 0x4d, 0x43, 0xd5, 0xb2, 0xab, 0x6b, 0x15, 0x7b, 0xe8, 0x96, 0x0f, 0xda, 0x03,
	0x38, 0x74, 0x29, 0x09, 0x64, 0x57, 0x5d, 0xfa, 0x7d, 0x49, 0xb9, 0xb0, 0x4f, 0xe0, 0xde, 0xda,
	0xc5, 0xd3, 0x24, 0xe6, 0x14, 0x1d, 0x68, 0xc9, 0xa7, 0xa8, 0x96, 0x77, 0x67, 0x56, 0xb5, 0x8e,
	0x3a, 0xa1, 0xf2, 0xec, 0x53, 0x18, 0x5c, 0xaa, 0x3e, 0x17, 0x0a, 0x6f, 0x5d, 0xe4, 0x0c, 0xb0,
	0x58, 0xe4, 0x3f, 0xaf, 0x32, 0x84, 0xc1, 0x19, 0x5d, 0xd0, 0xd2, 0x55, 0xec, 0x11, 0x60, 0xd1,
	0x99, 0x95, 0xb6, 0x7f, 0x35, 0xa0, 0x57, 0x6a, 0xfc, 0x16, 0xa0, 0xdd, 0x87, 0xb6, 0x94, 0xf3,
	0xc2, 0x0c, 0x34, 0xc3, 0xdd, 0x97, 0xe6, 0xbb, 0x00, 0x11, 0x5a, 0x62, 0x95, 0xe6, 0x84, 0xa9,
	0xff, 0x92, 0x3d, 0x9f, 0xb0, 0xc0, 0x9b, 0x33, 0x12, 0x07, 0x9a, 0x2e, 0x43, 0x7a, 0x4e, 0xa4,
	0x03, 0x1f, 0x41, 0x5f, 0x85, 0xe9, 0x75, 0xea, 0x45, 0x49, 0x2c, 0xae, 0x34, 0x67, 0x07, 0xd2,
	0xfb, 0xe6, 0x3a, 0xbd, 0x90, 0x3e, 0xb4, 0xa1, 0xf7, 0x27, 0x6b, 0x45, 0x09, 0xd3, 0xcc, 0x75,
	0x75, 0xd2, 0x67, 0x4a, 0x18, 0x3e, 0x00, 0x65, 0x7a, 0x0a, 0xe5, 0x63, 0xb3, 0xb3, 0x56, 0x3a,
	0x27, 0x5c, 0x1c, 0xdb, 0xcf, 0xc0, 0x3a, 0x55, 0x0f, 0x28, 0xf3, 0xa6, 0x07, 0xb6, 0xf1, 0x7a,
	0x99, 0x9d, 0x75, 0xed, 0x4e, 0xd9, 0x21, 0x8c, 0x2b, 0x6b, 0xeb, 0x39, 0xbe, 0x87, 0x7e, 0x79,
	0x23, 0xf4, 0x44, 0xef, 0xb4, 0x10, 0xbd, 0xd2, 0x42, 0xd8, 0x47, 0x30, 0xae, 0xbc, 0x58, 0x26,
	0x35, 0xfb, 0xd1, 0x82, 0xf6, 0xeb, 0xac, 0x0e, 0x7e, 0x81, 0x4e, 0x4e, 0x37, 0x3e, 0xae, 0x96,
	0xda, 0x58, 0x08, 0xeb, 0xc9, 0x6d, 0x69, 0x1a, 0x9f, 0x1d, 0x24, 0x00, 0x6b, 0x62, 0xf1, 0x69,
	0x0d, 0x9b, 0x9b, 0x8b, 0x61, 0x4d, 0x6f, 0x4f, 0x2c, 0x4a, 0xac, 0xc9, 0xad, 0x93, 0xf8, 0x0b,
	0xf8, 0x3a, 0x89, 0x8a, 0x25, 0xd8, 0xc1, 0x1b, 0x18, 0x56, 0x0c, 0x0e, 0x5f, 0x54, 0x97, 0xa8,
	0xe7, 0xc7, 0x7a, 0xb9, 0xc5, 0x09, 0x4d, 0xc5, 0x0d, 0x0c, 0x2b, 0x26, 0x59, 0xa7, 0x5d, 0x4f,
	0x63, 0x9d, 0xf6, 0x3f, 0x30, 0x99, 0xef, 0xab, 0x6f, 0xd1, 0xab, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xcc, 0x79, 0x96, 0xbf, 0xaa, 0x06, 0x00, 0x00,
}
