// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/micro/micro/v3/service/client"

	emails "github.com/m3o/services/emails/proto"

	mock "github.com/stretchr/testify/mock"
)

// EmailsService is an autogenerated mock type for the EmailsService type
type EmailsService struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, in, opts
func (_m *EmailsService) Send(ctx context.Context, in *emails.SendRequest, opts ...client.CallOption) (*emails.SendResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *emails.SendResponse
	if rf, ok := ret.Get(0).(func(context.Context, *emails.SendRequest, ...client.CallOption) *emails.SendResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emails.SendResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *emails.SendRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
