name: Build

on:
  push:

jobs:
  devel_docker_build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
         name: Check out repository
       - run: |
           GOPATH=~/go
           echo $GOPATH
       - uses: actions/cache@v1
         name: Cache
         with:
           path: ~/go/pkg/mod
           key: go-mod-cache
       - name: Build images
         run: |
           mkdir builds
           for dir in */; do
             cd $dir
             (CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build . && mv ./${dir::-1} ../builds/${dir::-1} || true)
             cd ..;
           done
