name: Build

on: 
  schedule:
    - cron: 0 0 29 2 1
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get previous release
      run: |
        data=$(curl -s https://api.github.com/repos/micro/services/releases/latest)
        zipURL=$(echo $data | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["assets"][0]["browser_download_url"]')
        cp zipURL builds
        ls -ll builds
        
