name: Build

on:
  push:

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: docker://micro/go-micro
         name: Base image
       - uses: actions/checkout@v2
         name: Check out repository
       - run: echo $GOPATH
       - uses: actions/cache@v1
         name: Cache
         with:
           path: ~/go/pkg/mod
           key: go-mod-cache
       - name: Build images
         run: |
           mkdir builds
           for dir in */; do
             cd $dir
             (CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build . && mv ./${dir::-1} ../builds/${dir::-1} || true)
             cd ..;
           done
