name: Build

on:
  push:

jobs:
  devel_docker_build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
         name: Check out repository
       - uses: actions/checkout@v2
       - name: Build and Push Docker Image
         run: |
           echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
           docker build . -t micro/services:${GITHUB_REF##*/}
           docker push micro/services:${GITHUB_REF##*/}
