name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: go-mod-cache
    - name: Build images
      run: |
         mkdir builds
         for dir in */; do
           cd $dir
           (CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build . && mv ./${dir::-1} ../builds/${dir::-1} || true)
           cd ..;
         done
