name: Build

on:
  push:

jobs:
  devel_docker_build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
         name: Check out repository
       - uses: azure/docker-login@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Build and Push Docker Image
         run: |
           sh echo ${{ secrets. }} | docker login -u ${{ secrets. }} --password-stdin
           docker build . -t micro/services:${GITHUB_REF##*/}
           docker push micro/services:${GITHUB_REF##*/}
