name: Build

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Detect which services changed
      id: services_changed
      uses: micro/actions@1.0.0
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Build Started Webhook
      run: |
        ./event.sh "build.started" "${GITHUB_SHA}" "${GITHUB_REPOSITORY}"
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Setup go-mod cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-gomods-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-gomods-
    - name: Setup dumb init
      run: |
        git clone https://github.com/Yelp/dumb-init.git
        cd dumb-init
        make build
        cd ..
    - name: Build and push docker images
      run: |
        # Setup tmp directory and add dumb-init (used by docker images)
        mkdir tmp
        cp dumb-init/dumb-init tmp/dumb-init
          
        # Login to docker
        echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin docker.pkg.github.com

        # Build the binaries in the directories which have changed
        ./build.sh ${{ github.repository }} "${{ steps.services_changed.outputs.services }})"

        # Tidy up the tmp dir
        rm -rf tmp
    - name: Build Finished Webhook
      run: |
        ./event.sh "build.finished" "${GITHUB_SHA}" "${GITHUB_REPOSITORY}"
    - name: Build Failed Webhook
      if: failure()
      run: |
        ./event.sh "build.failed" "${GITHUB_SHA}" "${GITHUB_REPOSITORY}"
