name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Setup go-mod cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-gomods-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-gomods-
    - name: Setup build cache
      id: setup-build-cache
      uses: actions/cache@v1
      with:
        path: /builds
        key: ${{ runner.os }}-builds-${{ hashFiles('**/*.go') }}
        restore-keys: |
          ${{ runner.os }}-builds-
    - name: Generate build dir
      if: steps.setup-build-cache.outputs.cache-hit != 'true'
      run: mkdir builds
    - name: Build images
      run: |
         for dir in */; do
           cd $dir
           (CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build . && mv ./${dir::-1} ../builds/${dir::-1} || true)
           cd ..;
         done
