name: CI

on:
  push:
    branches-ignore: master

jobs:
  devel_docker_build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
       - id: file_changes
         uses: trilom/file-changes-action@v1
         with:
           githubToken: ${{ secrets.GH_TOKEN }}
       - name: testr
         run: |
            cat $HOME/files.json
       - name: webhook-start
         uses: wei/curl@master
         with:
           args: "https://46dfac7c.ngrok.io/platform/v1/github/build-started -X POST -d $HOME/files.json -H \"Content-Type: application/json\""
       - uses: actions/checkout@v2
         name: Check out repository
       - uses: elgohr/Publish-Docker-Github-Action@2.12
         name: Build and Push Docker Image
         with:
           name: micro/services
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
       - name: webhook-end
         uses: wei/curl@master
         with:
           args: https://micro.mu/platform/v1/github/build-finished
