name: CI

on:
  push:
    branches-ignore: master

jobs:
  devel_docker_build:
     runs-on: ubuntu-latest
     steps:
       - name: webhook-start
         uses: wei/curl@master
         with:
           args: https://micro.mu/platform/v1/github/build-started
       - uses: actions/checkout@v2
         name: Check out repository
       - uses: elgohr/Publish-Docker-Github-Action@2.12
         name: Build and Push Docker Image
         with:
           name: micro/services
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
       - name: webhook-end
         uses: wei/curl@master
         with:
           args: https://micro.mu/platform/v1/github/build-finished
