name: Docker

on:
  push:
    branches:
      - master

jobs:
  build-cockroach-backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - uses: elgohr/Publish-Docker-Github-Action@2.18
        name: Build and Push Docker Image
        with:
          name: m3o/cockroach-backup
          username: ${{ secrets.GHCR_ACTOR }}
          password: ${{ secrets.GHCR_PAT }}
          workdir: database/backup
          snapshot: true
          registry: ghcr.io
  build-cockroach-restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - uses: elgohr/Publish-Docker-Github-Action@2.18
        name: Build and Push Docker Image
        with:
          name: m3o/cockroach-restore
          username: ${{ secrets.GHCR_ACTOR }}
          password: ${{ secrets.GHCR_PAT }}
          workdir: database/restore
          snapshot: true
          registry: ghcr.io
