name: M3O integration tests
# NOTE: if this is running on a self hosted runner do not change to pull_request otherwise
# you have a big security risk https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories
on: [push]

jobs:

  test:
    name: Micro server m3o integration tests
    runs-on: self-hosted
    steps:
    - uses: satackey/action-docker-layer-caching@v0.0.8
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go

    - name: Install Protoc
      uses: arduino/setup-protoc@master

    - name: Check out this code
      uses: actions/checkout@v2
      with:
        path: services
    
    - name: Check out micro code
      uses: actions/checkout@v2
      with:
        repository: 'micro/micro'
        path: 'micro'
        ref: '2bc730ad54f2f5afbadab121005b462a8a938667'

    - name: Install micro
      working-directory: micro
      run: |
        go run . init --profile=ci --output=profile.go
        go mod edit -replace github.com/micro/micro/profile/ci/v3=./profile/ci
        go mod edit -replace google.golang.org/grpc=google.golang.org/grpc@v1.26.0
        go install

    - name: Build container
      run: |
        bash services/tests/image/test-docker.sh

    - name: Test M3O services
      working-directory: services/tests
      run: |
          # Generate keys for JWT tests
          ssh-keygen -f /tmp/sshkey -m pkcs8 -q -N "" || true
          ssh-keygen -f /tmp/sshkey -e  -m pkcs8 > /tmp/sshkey.pub || true
          go clean -testcache && go test -timeout 15m --tags=m3o -v ./...
      env:
        MICRO_STRIPE_API_KEY: ${{ secrets.MICRO_STRIPE_API_KEY }}
        MICRO_SENDGRID_API_KEY: ${{ secrets.MICRO_SENDGRID_API_KEY }}
        MICRO_SENDGRID_TEMPLATE_ID: ${{ secrets.MICRO_SENDGRID_TEMPLATE_ID }}
        MICRO_STRIPE_PLAN_ID: ${{ secrets.MICRO_STRIPE_PLAN_ID }}
        MICRO_SENDGRID_INVITE_TEMPLATE_ID: ${{ secrets.MICRO_SENDGRID_INVITE_TEMPLATE_ID }}
        MICRO_STRIPE_ADDITIONAL_USERS_PRICE_ID: ${{ secrets.MICRO_STRIPE_ADDITIONAL_USERS_PRICE_ID }}
        MICRO_STRIPE_ADDITIONAL_SERVICES_PRICE_ID: ${{ secrets.MICRO_STRIPE_ADDITIONAL_SERVICES_PRICE_ID }}
        MICRO_EMAIL_FROM: ${{ secrets.MICRO_EMAIL_FROM }}
        MICRO_TEST_ENV: ${{ secrets.MICRO_TEST_ENV }}
        M3O_STRIPE_SVC: ../../../payments/provider/stripe
        M3O_SIGNUP_SVC: ../../../signup
        M3O_INVITE_SVC: ../../../invite
        
