// Code generated by protoc-gen-go. DO NOT EDIT.
// source: micro/services/platform/api/proto/api.proto

package go_micro_api_platform

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SpanType int32

const (
	SpanType_INBOUND  SpanType = 0
	SpanType_OUTBOUND SpanType = 1
)

var SpanType_name = map[int32]string{
	0: "INBOUND",
	1: "OUTBOUND",
}

var SpanType_value = map[string]int32{
	"INBOUND":  0,
	"OUTBOUND": 1,
}

func (x SpanType) String() string {
	return proto.EnumName(SpanType_name, int32(x))
}

func (SpanType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{0}
}

type ReadUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserRequest) Reset()         { *m = ReadUserRequest{} }
func (m *ReadUserRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUserRequest) ProtoMessage()    {}
func (*ReadUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{0}
}

func (m *ReadUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserRequest.Unmarshal(m, b)
}
func (m *ReadUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserRequest.Marshal(b, m, deterministic)
}
func (m *ReadUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserRequest.Merge(m, src)
}
func (m *ReadUserRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUserRequest.Size(m)
}
func (m *ReadUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserRequest proto.InternalMessageInfo

type ReadUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserResponse) Reset()         { *m = ReadUserResponse{} }
func (m *ReadUserResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUserResponse) ProtoMessage()    {}
func (*ReadUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{1}
}

func (m *ReadUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserResponse.Unmarshal(m, b)
}
func (m *ReadUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserResponse.Marshal(b, m, deterministic)
}
func (m *ReadUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserResponse.Merge(m, src)
}
func (m *ReadUserResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUserResponse.Size(m)
}
func (m *ReadUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserResponse proto.InternalMessageInfo

func (m *ReadUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServiceRequest) Reset()         { *m = CreateServiceRequest{} }
func (m *CreateServiceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateServiceRequest) ProtoMessage()    {}
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{2}
}

func (m *CreateServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceRequest.Unmarshal(m, b)
}
func (m *CreateServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceRequest.Marshal(b, m, deterministic)
}
func (m *CreateServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceRequest.Merge(m, src)
}
func (m *CreateServiceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateServiceRequest.Size(m)
}
func (m *CreateServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceRequest proto.InternalMessageInfo

func (m *CreateServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type CreateServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServiceResponse) Reset()         { *m = CreateServiceResponse{} }
func (m *CreateServiceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateServiceResponse) ProtoMessage()    {}
func (*CreateServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{3}
}

func (m *CreateServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceResponse.Unmarshal(m, b)
}
func (m *CreateServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceResponse.Marshal(b, m, deterministic)
}
func (m *CreateServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceResponse.Merge(m, src)
}
func (m *CreateServiceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateServiceResponse.Size(m)
}
func (m *CreateServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceResponse proto.InternalMessageInfo

type ReadServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadServiceRequest) Reset()         { *m = ReadServiceRequest{} }
func (m *ReadServiceRequest) String() string { return proto.CompactTextString(m) }
func (*ReadServiceRequest) ProtoMessage()    {}
func (*ReadServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{4}
}

func (m *ReadServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadServiceRequest.Unmarshal(m, b)
}
func (m *ReadServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadServiceRequest.Marshal(b, m, deterministic)
}
func (m *ReadServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadServiceRequest.Merge(m, src)
}
func (m *ReadServiceRequest) XXX_Size() int {
	return xxx_messageInfo_ReadServiceRequest.Size(m)
}
func (m *ReadServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadServiceRequest proto.InternalMessageInfo

func (m *ReadServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type ReadServiceResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReadServiceResponse) Reset()         { *m = ReadServiceResponse{} }
func (m *ReadServiceResponse) String() string { return proto.CompactTextString(m) }
func (*ReadServiceResponse) ProtoMessage()    {}
func (*ReadServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{5}
}

func (m *ReadServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadServiceResponse.Unmarshal(m, b)
}
func (m *ReadServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadServiceResponse.Marshal(b, m, deterministic)
}
func (m *ReadServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadServiceResponse.Merge(m, src)
}
func (m *ReadServiceResponse) XXX_Size() int {
	return xxx_messageInfo_ReadServiceResponse.Size(m)
}
func (m *ReadServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadServiceResponse proto.InternalMessageInfo

func (m *ReadServiceResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type UpdateServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateServiceRequest) Reset()         { *m = UpdateServiceRequest{} }
func (m *UpdateServiceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateServiceRequest) ProtoMessage()    {}
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{6}
}

func (m *UpdateServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateServiceRequest.Unmarshal(m, b)
}
func (m *UpdateServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateServiceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateServiceRequest.Merge(m, src)
}
func (m *UpdateServiceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateServiceRequest.Size(m)
}
func (m *UpdateServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateServiceRequest proto.InternalMessageInfo

func (m *UpdateServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type UpdateServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateServiceResponse) Reset()         { *m = UpdateServiceResponse{} }
func (m *UpdateServiceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateServiceResponse) ProtoMessage()    {}
func (*UpdateServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{7}
}

func (m *UpdateServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateServiceResponse.Unmarshal(m, b)
}
func (m *UpdateServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateServiceResponse.Marshal(b, m, deterministic)
}
func (m *UpdateServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateServiceResponse.Merge(m, src)
}
func (m *UpdateServiceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateServiceResponse.Size(m)
}
func (m *UpdateServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateServiceResponse proto.InternalMessageInfo

type DeleteServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteServiceRequest) Reset()         { *m = DeleteServiceRequest{} }
func (m *DeleteServiceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteServiceRequest) ProtoMessage()    {}
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{8}
}

func (m *DeleteServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteServiceRequest.Unmarshal(m, b)
}
func (m *DeleteServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteServiceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteServiceRequest.Merge(m, src)
}
func (m *DeleteServiceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteServiceRequest.Size(m)
}
func (m *DeleteServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteServiceRequest proto.InternalMessageInfo

func (m *DeleteServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type DeleteServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteServiceResponse) Reset()         { *m = DeleteServiceResponse{} }
func (m *DeleteServiceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteServiceResponse) ProtoMessage()    {}
func (*DeleteServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{9}
}

func (m *DeleteServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteServiceResponse.Unmarshal(m, b)
}
func (m *DeleteServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteServiceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteServiceResponse.Merge(m, src)
}
func (m *DeleteServiceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteServiceResponse.Size(m)
}
func (m *DeleteServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteServiceResponse proto.InternalMessageInfo

type ListServicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServicesRequest) Reset()         { *m = ListServicesRequest{} }
func (m *ListServicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListServicesRequest) ProtoMessage()    {}
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{10}
}

func (m *ListServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesRequest.Unmarshal(m, b)
}
func (m *ListServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesRequest.Marshal(b, m, deterministic)
}
func (m *ListServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesRequest.Merge(m, src)
}
func (m *ListServicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListServicesRequest.Size(m)
}
func (m *ListServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesRequest proto.InternalMessageInfo

type ListServicesResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListServicesResponse) Reset()         { *m = ListServicesResponse{} }
func (m *ListServicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListServicesResponse) ProtoMessage()    {}
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{11}
}

func (m *ListServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesResponse.Unmarshal(m, b)
}
func (m *ListServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesResponse.Marshal(b, m, deterministic)
}
func (m *ListServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesResponse.Merge(m, src)
}
func (m *ListServicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListServicesResponse.Size(m)
}
func (m *ListServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesResponse proto.InternalMessageInfo

func (m *ListServicesResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	Name     string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version  string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Source   string            `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Type     string            `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Metadata map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Addition to support stats endpoint
	Node                 *Node    `protobuf:"bytes,6,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{12}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Service) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Service) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Service) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Service) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type User struct {
	Name                  string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                 string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Login                 string   `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	AvatarUrl             string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	TeamName              string   `protobuf:"bytes,5,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	TeamUrl               string   `protobuf:"bytes,6,opt,name=team_url,json=teamUrl,proto3" json:"team_url,omitempty"`
	OrganizationAvatarUrl string   `protobuf:"bytes,7,opt,name=organization_avatar_url,json=organizationAvatarUrl,proto3" json:"organization_avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{13}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *User) GetTeamName() string {
	if m != nil {
		return m.TeamName
	}
	return ""
}

func (m *User) GetTeamUrl() string {
	if m != nil {
		return m.TeamUrl
	}
	return ""
}

func (m *User) GetOrganizationAvatarUrl() string {
	if m != nil {
		return m.OrganizationAvatarUrl
	}
	return ""
}

// Node describes a single instance of a service.
type Node struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{14}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// Snapshot is a snapshot of Debug.Stats from a particular service when called.
type StatSnapshot struct {
	Service *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Unix timestamp, e.g. 1575561487
	Started int64 `protobuf:"varint,2,opt,name=started,proto3" json:"started,omitempty"`
	// Uptime in seconds
	Uptime uint64 `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// Heap allocated in bytes (TODO: change to resident set size)
	Memory uint64 `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	// Number of Goroutines
	Threads uint64 `protobuf:"varint,5,opt,name=threads,proto3" json:"threads,omitempty"`
	// GC Pause total in ns
	Gc uint64 `protobuf:"varint,6,opt,name=gc,proto3" json:"gc,omitempty"`
	// Total number of request
	Requests uint64 `protobuf:"varint,7,opt,name=requests,proto3" json:"requests,omitempty"`
	// Total number of errors
	Errors uint64 `protobuf:"varint,8,opt,name=errors,proto3" json:"errors,omitempty"`
	// Timestamp at the time of the taking of the snapshot, seconds since unix epoch
	Timestamp            uint64   `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatSnapshot) Reset()         { *m = StatSnapshot{} }
func (m *StatSnapshot) String() string { return proto.CompactTextString(m) }
func (*StatSnapshot) ProtoMessage()    {}
func (*StatSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{15}
}

func (m *StatSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatSnapshot.Unmarshal(m, b)
}
func (m *StatSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatSnapshot.Marshal(b, m, deterministic)
}
func (m *StatSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatSnapshot.Merge(m, src)
}
func (m *StatSnapshot) XXX_Size() int {
	return xxx_messageInfo_StatSnapshot.Size(m)
}
func (m *StatSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_StatSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_StatSnapshot proto.InternalMessageInfo

func (m *StatSnapshot) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *StatSnapshot) GetStarted() int64 {
	if m != nil {
		return m.Started
	}
	return 0
}

func (m *StatSnapshot) GetUptime() uint64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *StatSnapshot) GetMemory() uint64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *StatSnapshot) GetThreads() uint64 {
	if m != nil {
		return m.Threads
	}
	return 0
}

func (m *StatSnapshot) GetGc() uint64 {
	if m != nil {
		return m.Gc
	}
	return 0
}

func (m *StatSnapshot) GetRequests() uint64 {
	if m != nil {
		return m.Requests
	}
	return 0
}

func (m *StatSnapshot) GetErrors() uint64 {
	if m != nil {
		return m.Errors
	}
	return 0
}

func (m *StatSnapshot) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type StatsRequest struct {
	// If set, only return services matching the filter
	Service *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// If false, only the current snapshots will be returned.
	// If true, all historical snapshots in memory will be returned.
	Past                 bool     `protobuf:"varint,2,opt,name=past,proto3" json:"past,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsRequest) Reset()         { *m = StatsRequest{} }
func (m *StatsRequest) String() string { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()    {}
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{16}
}

func (m *StatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsRequest.Unmarshal(m, b)
}
func (m *StatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsRequest.Marshal(b, m, deterministic)
}
func (m *StatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsRequest.Merge(m, src)
}
func (m *StatsRequest) XXX_Size() int {
	return xxx_messageInfo_StatsRequest.Size(m)
}
func (m *StatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatsRequest proto.InternalMessageInfo

func (m *StatsRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *StatsRequest) GetPast() bool {
	if m != nil {
		return m.Past
	}
	return false
}

type StatsResponse struct {
	Stats                []*StatSnapshot `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StatsResponse) Reset()         { *m = StatsResponse{} }
func (m *StatsResponse) String() string { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()    {}
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{17}
}

func (m *StatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsResponse.Unmarshal(m, b)
}
func (m *StatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsResponse.Marshal(b, m, deterministic)
}
func (m *StatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsResponse.Merge(m, src)
}
func (m *StatsResponse) XXX_Size() int {
	return xxx_messageInfo_StatsResponse.Size(m)
}
func (m *StatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatsResponse proto.InternalMessageInfo

func (m *StatsResponse) GetStats() []*StatSnapshot {
	if m != nil {
		return m.Stats
	}
	return nil
}

type Record struct {
	// timestamp of log record
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// record metadata
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// record value
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{18}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Record) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Record) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LogsRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogsRequest) Reset()         { *m = LogsRequest{} }
func (m *LogsRequest) String() string { return proto.CompactTextString(m) }
func (*LogsRequest) ProtoMessage()    {}
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{19}
}

func (m *LogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogsRequest.Unmarshal(m, b)
}
func (m *LogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogsRequest.Marshal(b, m, deterministic)
}
func (m *LogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogsRequest.Merge(m, src)
}
func (m *LogsRequest) XXX_Size() int {
	return xxx_messageInfo_LogsRequest.Size(m)
}
func (m *LogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogsRequest proto.InternalMessageInfo

func (m *LogsRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *LogsRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LogsResponse struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LogsResponse) Reset()         { *m = LogsResponse{} }
func (m *LogsResponse) String() string { return proto.CompactTextString(m) }
func (*LogsResponse) ProtoMessage()    {}
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{20}
}

func (m *LogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogsResponse.Unmarshal(m, b)
}
func (m *LogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogsResponse.Marshal(b, m, deterministic)
}
func (m *LogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogsResponse.Merge(m, src)
}
func (m *LogsResponse) XXX_Size() int {
	return xxx_messageInfo_LogsResponse.Size(m)
}
func (m *LogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogsResponse proto.InternalMessageInfo

func (m *LogsResponse) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type Span struct {
	// the trace id
	Trace string `protobuf:"bytes,1,opt,name=trace,proto3" json:"trace,omitempty"`
	// id of the span
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// parent span
	Parent string `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	// name of the resource
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// time of start in nanoseconds
	Started uint64 `protobuf:"varint,5,opt,name=started,proto3" json:"started,omitempty"`
	// duration of the execution in nanoseconds
	Duration uint64 `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	// associated metadata
	Metadata             map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Type                 SpanType          `protobuf:"varint,8,opt,name=type,proto3,enum=go.micro.api.platform.SpanType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Span) Reset()         { *m = Span{} }
func (m *Span) String() string { return proto.CompactTextString(m) }
func (*Span) ProtoMessage()    {}
func (*Span) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{21}
}

func (m *Span) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span.Unmarshal(m, b)
}
func (m *Span) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span.Marshal(b, m, deterministic)
}
func (m *Span) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span.Merge(m, src)
}
func (m *Span) XXX_Size() int {
	return xxx_messageInfo_Span.Size(m)
}
func (m *Span) XXX_DiscardUnknown() {
	xxx_messageInfo_Span.DiscardUnknown(m)
}

var xxx_messageInfo_Span proto.InternalMessageInfo

func (m *Span) GetTrace() string {
	if m != nil {
		return m.Trace
	}
	return ""
}

func (m *Span) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Span) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Span) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Span) GetStarted() uint64 {
	if m != nil {
		return m.Started
	}
	return 0
}

func (m *Span) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Span) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Span) GetType() SpanType {
	if m != nil {
		return m.Type
	}
	return SpanType_INBOUND
}

type TracesRequest struct {
	// If set, only return services matching the filter
	Service *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// If false, only the current snapshots will be returned.
	// If true, all historical snapshots in memory will be returned.
	Past bool `protobuf:"varint,2,opt,name=past,proto3" json:"past,omitempty"`
	// Number of traces to return
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TracesRequest) Reset()         { *m = TracesRequest{} }
func (m *TracesRequest) String() string { return proto.CompactTextString(m) }
func (*TracesRequest) ProtoMessage()    {}
func (*TracesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{22}
}

func (m *TracesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TracesRequest.Unmarshal(m, b)
}
func (m *TracesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TracesRequest.Marshal(b, m, deterministic)
}
func (m *TracesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TracesRequest.Merge(m, src)
}
func (m *TracesRequest) XXX_Size() int {
	return xxx_messageInfo_TracesRequest.Size(m)
}
func (m *TracesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TracesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TracesRequest proto.InternalMessageInfo

func (m *TracesRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *TracesRequest) GetPast() bool {
	if m != nil {
		return m.Past
	}
	return false
}

func (m *TracesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type TracesResponse struct {
	Spans                []*Span  `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TracesResponse) Reset()         { *m = TracesResponse{} }
func (m *TracesResponse) String() string { return proto.CompactTextString(m) }
func (*TracesResponse) ProtoMessage()    {}
func (*TracesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e14e5b6fd5206, []int{23}
}

func (m *TracesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TracesResponse.Unmarshal(m, b)
}
func (m *TracesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TracesResponse.Marshal(b, m, deterministic)
}
func (m *TracesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TracesResponse.Merge(m, src)
}
func (m *TracesResponse) XXX_Size() int {
	return xxx_messageInfo_TracesResponse.Size(m)
}
func (m *TracesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TracesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TracesResponse proto.InternalMessageInfo

func (m *TracesResponse) GetSpans() []*Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

func init() {
	proto.RegisterEnum("go.micro.api.platform.SpanType", SpanType_name, SpanType_value)
	proto.RegisterType((*ReadUserRequest)(nil), "go.micro.api.platform.ReadUserRequest")
	proto.RegisterType((*ReadUserResponse)(nil), "go.micro.api.platform.ReadUserResponse")
	proto.RegisterType((*CreateServiceRequest)(nil), "go.micro.api.platform.CreateServiceRequest")
	proto.RegisterType((*CreateServiceResponse)(nil), "go.micro.api.platform.CreateServiceResponse")
	proto.RegisterType((*ReadServiceRequest)(nil), "go.micro.api.platform.ReadServiceRequest")
	proto.RegisterType((*ReadServiceResponse)(nil), "go.micro.api.platform.ReadServiceResponse")
	proto.RegisterType((*UpdateServiceRequest)(nil), "go.micro.api.platform.UpdateServiceRequest")
	proto.RegisterType((*UpdateServiceResponse)(nil), "go.micro.api.platform.UpdateServiceResponse")
	proto.RegisterType((*DeleteServiceRequest)(nil), "go.micro.api.platform.DeleteServiceRequest")
	proto.RegisterType((*DeleteServiceResponse)(nil), "go.micro.api.platform.DeleteServiceResponse")
	proto.RegisterType((*ListServicesRequest)(nil), "go.micro.api.platform.ListServicesRequest")
	proto.RegisterType((*ListServicesResponse)(nil), "go.micro.api.platform.ListServicesResponse")
	proto.RegisterType((*Service)(nil), "go.micro.api.platform.Service")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.api.platform.Service.MetadataEntry")
	proto.RegisterType((*User)(nil), "go.micro.api.platform.User")
	proto.RegisterType((*Node)(nil), "go.micro.api.platform.Node")
	proto.RegisterType((*StatSnapshot)(nil), "go.micro.api.platform.StatSnapshot")
	proto.RegisterType((*StatsRequest)(nil), "go.micro.api.platform.StatsRequest")
	proto.RegisterType((*StatsResponse)(nil), "go.micro.api.platform.StatsResponse")
	proto.RegisterType((*Record)(nil), "go.micro.api.platform.Record")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.api.platform.Record.MetadataEntry")
	proto.RegisterType((*LogsRequest)(nil), "go.micro.api.platform.LogsRequest")
	proto.RegisterType((*LogsResponse)(nil), "go.micro.api.platform.LogsResponse")
	proto.RegisterType((*Span)(nil), "go.micro.api.platform.Span")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.api.platform.Span.MetadataEntry")
	proto.RegisterType((*TracesRequest)(nil), "go.micro.api.platform.TracesRequest")
	proto.RegisterType((*TracesResponse)(nil), "go.micro.api.platform.TracesResponse")
}

func init() {
	proto.RegisterFile("micro/services/platform/api/proto/api.proto", fileDescriptor_a97e14e5b6fd5206)
}

var fileDescriptor_a97e14e5b6fd5206 = []byte{
	// 1051 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xef, 0x6e, 0x1b, 0x45,
	0x10, 0x8f, 0xcf, 0x67, 0xfb, 0x3c, 0xf9, 0x43, 0xd8, 0x3a, 0xed, 0xe1, 0x50, 0xa8, 0xae, 0x2d,
	0xd0, 0xa6, 0xb2, 0x21, 0x95, 0xa0, 0x94, 0x4f, 0x25, 0xad, 0x0a, 0xa8, 0xb8, 0xe9, 0x26, 0x16,
	0x5f, 0x40, 0xd1, 0xe2, 0xdb, 0xba, 0x27, 0x7c, 0xb7, 0xc7, 0xee, 0x3a, 0x92, 0x79, 0x02, 0x3e,
	0xf1, 0x02, 0xbc, 0x0f, 0x3c, 0x01, 0xef, 0x83, 0xf6, 0xdf, 0xc5, 0x17, 0xf9, 0xae, 0x91, 0x92,
	0x7e, 0xdb, 0x99, 0x9b, 0xf9, 0xcd, 0xce, 0x6f, 0x67, 0xc6, 0x63, 0xd8, 0x4b, 0x93, 0x09, 0x67,
	0x43, 0x41, 0xf9, 0x69, 0x32, 0xa1, 0x62, 0x98, 0xcf, 0x88, 0x7c, 0xcd, 0x78, 0x3a, 0x24, 0x79,
	0x32, 0xcc, 0x39, 0x93, 0x4c, 0x9d, 0x06, 0xfa, 0x84, 0x76, 0xa6, 0x6c, 0xa0, 0xed, 0x07, 0x5a,
	0x67, 0x4d, 0xa3, 0xf7, 0xe1, 0x3d, 0x4c, 0x49, 0x3c, 0x16, 0x94, 0x63, 0xfa, 0xfb, 0x9c, 0x0a,
	0x19, 0x1d, 0xc0, 0xf6, 0x99, 0x4a, 0xe4, 0x2c, 0x13, 0x14, 0x0d, 0xc1, 0x9f, 0x0b, 0xca, 0xc3,
	0xc6, 0xad, 0xc6, 0x67, 0xeb, 0xfb, 0xbb, 0x83, 0x95, 0x60, 0x03, 0xed, 0xa2, 0x0d, 0xa3, 0x43,
	0xe8, 0x1d, 0x70, 0x4a, 0x24, 0x3d, 0x32, 0xb7, 0xb3, 0xe0, 0xe8, 0x11, 0x74, 0xec, 0x7d, 0x2d,
	0xd6, 0x47, 0x15, 0x58, 0xce, 0xcf, 0x99, 0x47, 0x37, 0x60, 0xe7, 0x1c, 0xa2, 0xb9, 0x5b, 0x34,
	0x02, 0xa4, 0xee, 0x7b, 0x65, 0x81, 0x5e, 0xc1, 0xb5, 0x12, 0x9e, 0xa5, 0xe0, 0x31, 0x04, 0x8e,
	0xe9, 0xb0, 0x71, 0xab, 0x79, 0x01, 0xc4, 0xc2, 0x5e, 0xb1, 0x31, 0xce, 0xe3, 0x2b, 0x66, 0xe3,
	0x1c, 0xa2, 0x65, 0xe3, 0x10, 0x7a, 0x4f, 0xe9, 0x8c, 0x5e, 0x6d, 0xa8, 0x73, 0x88, 0x36, 0xd4,
	0x0e, 0x5c, 0x7b, 0x91, 0x08, 0x69, 0xd5, 0xc2, 0xd5, 0x0f, 0x86, 0x5e, 0x59, 0x7d, 0x05, 0x04,
	0xfe, 0xed, 0x41, 0xc7, 0x6a, 0x11, 0x02, 0x3f, 0x23, 0xa9, 0x49, 0xa3, 0x8b, 0xf5, 0x19, 0x85,
	0xd0, 0x39, 0xa5, 0x5c, 0x24, 0x2c, 0x0b, 0x3d, 0xad, 0x76, 0x22, 0xba, 0x0e, 0x6d, 0xc1, 0xe6,
	0x7c, 0x42, 0xc3, 0xa6, 0xfe, 0x60, 0x25, 0x85, 0x22, 0x17, 0x39, 0x0d, 0x7d, 0x83, 0xa2, 0xce,
	0xe8, 0x3b, 0x08, 0x52, 0x2a, 0x49, 0x4c, 0x24, 0x09, 0x5b, 0xfa, 0x86, 0x0f, 0xea, 0x6f, 0x38,
	0xf8, 0xd1, 0x9a, 0x3f, 0xcb, 0x24, 0x5f, 0xe0, 0xc2, 0x5b, 0xf5, 0x4b, 0xc6, 0x62, 0x1a, 0xb6,
	0x6b, 0xfb, 0x65, 0xc4, 0x62, 0x8a, 0xb5, 0x61, 0xff, 0x1b, 0xd8, 0x2c, 0x61, 0xa1, 0x6d, 0x68,
	0xfe, 0x46, 0x17, 0x36, 0x49, 0x75, 0x44, 0x3d, 0x68, 0x9d, 0x92, 0xd9, 0x9c, 0xda, 0x0c, 0x8d,
	0xf0, 0xd8, 0x7b, 0xd4, 0x88, 0xfe, 0x6b, 0x80, 0xaf, 0x7a, 0x6f, 0x25, 0x35, 0x3d, 0x68, 0xd1,
	0x94, 0x24, 0x33, 0xe7, 0xa6, 0x05, 0xa5, 0x9d, 0xb1, 0x69, 0x92, 0x59, 0x56, 0x8c, 0x80, 0x6e,
	0x02, 0x90, 0x53, 0x22, 0x09, 0x3f, 0x99, 0xf3, 0x99, 0xa5, 0xa6, 0x6b, 0x34, 0x63, 0x3e, 0x43,
	0xbb, 0xd0, 0x95, 0x94, 0xa4, 0x27, 0x3a, 0x46, 0x4b, 0x7f, 0x0d, 0x94, 0x62, 0xa4, 0xe2, 0x7c,
	0x00, 0xfa, 0xac, 0x3d, 0xdb, 0xe6, 0x0d, 0x94, 0xac, 0xfc, 0xbe, 0x84, 0x1b, 0x8c, 0x4f, 0x49,
	0x96, 0xfc, 0x41, 0x64, 0xc2, 0xb2, 0x93, 0xa5, 0x18, 0x1d, 0x6d, 0xb9, 0xb3, 0xfc, 0xf9, 0x89,
	0x8b, 0x17, 0x7d, 0x0e, 0xbe, 0xa2, 0x08, 0x6d, 0x81, 0x97, 0xc4, 0x36, 0x29, 0x2f, 0x89, 0xd5,
	0x6b, 0x93, 0x38, 0xe6, 0x54, 0x08, 0xf7, 0xda, 0x56, 0x8c, 0xfe, 0xf2, 0x60, 0xe3, 0x48, 0x12,
	0x79, 0x94, 0x91, 0x5c, 0xbc, 0x61, 0x97, 0x28, 0x7b, 0x15, 0x44, 0x48, 0xc2, 0x25, 0x8d, 0x75,
	0x90, 0x26, 0x76, 0xa2, 0x2a, 0xa9, 0x79, 0x2e, 0x93, 0xd4, 0x94, 0x94, 0x8f, 0xad, 0xa4, 0xf4,
	0x29, 0x4d, 0x19, 0x5f, 0x68, 0xe6, 0x7c, 0x6c, 0x25, 0x85, 0x24, 0xdf, 0x70, 0x4a, 0x62, 0xa1,
	0x49, 0xf3, 0xb1, 0x13, 0x55, 0x62, 0xd3, 0x89, 0x66, 0xcb, 0xc7, 0xde, 0x74, 0x82, 0xfa, 0x10,
	0x70, 0xd3, 0x45, 0x42, 0x33, 0xe3, 0xe3, 0x42, 0x56, 0xe8, 0x94, 0x73, 0xc6, 0x45, 0x18, 0x18,
	0x74, 0x23, 0xa1, 0x0f, 0xa1, 0xab, 0xa2, 0x0b, 0x49, 0xd2, 0x3c, 0xec, 0xea, 0x4f, 0x67, 0x8a,
	0xe8, 0x67, 0xc3, 0x87, 0xb8, 0xf4, 0x18, 0x50, 0xb5, 0x95, 0x13, 0x21, 0x35, 0x19, 0x01, 0xd6,
	0xe7, 0xe8, 0x07, 0xd8, 0xb4, 0xe8, 0xb6, 0xc7, 0xbf, 0x86, 0x96, 0x50, 0x0a, 0xdb, 0xe0, 0xb7,
	0xab, 0xc0, 0x97, 0x9e, 0x08, 0x1b, 0x8f, 0xe8, 0x9f, 0x06, 0xb4, 0x31, 0x9d, 0x30, 0x1e, 0x97,
	0x53, 0x6a, 0x68, 0xf2, 0xcf, 0x14, 0xe8, 0xf9, 0x52, 0x97, 0x7a, 0x3a, 0xcc, 0x5e, 0x45, 0x18,
	0x03, 0x57, 0xd9, 0xa4, 0x21, 0x74, 0x52, 0x2a, 0x04, 0x99, 0xba, 0xd9, 0xe0, 0xc4, 0xcb, 0x75,
	0xe3, 0x13, 0x58, 0x7f, 0xc1, 0xa6, 0x05, 0xe3, 0x61, 0x99, 0xf1, 0x6e, 0xa9, 0xc2, 0x56, 0x0f,
	0xad, 0xe8, 0x39, 0x6c, 0x18, 0x08, 0x4b, 0xeb, 0x57, 0xd0, 0xe1, 0x3a, 0x17, 0x47, 0xec, 0xcd,
	0xda, 0x8c, 0xb1, 0xb3, 0x8e, 0xfe, 0xf5, 0xc0, 0x3f, 0xca, 0x49, 0xa6, 0xae, 0x2b, 0x39, 0x29,
	0xee, 0x60, 0x04, 0xdb, 0x58, 0x5e, 0xd1, 0x58, 0xd7, 0xa1, 0x9d, 0x13, 0x4e, 0x33, 0xe9, 0x86,
	0xa5, 0x91, 0x8a, 0xb9, 0xe2, 0x97, 0x47, 0xae, 0xeb, 0x0f, 0x5b, 0xd5, 0xae, 0x3f, 0xfa, 0x10,
	0xc4, 0x73, 0xae, 0x7b, 0xd9, 0xd6, 0x76, 0x21, 0xa3, 0x67, 0x4b, 0x8f, 0xd7, 0xd1, 0xa9, 0xdc,
	0xab, 0xaa, 0x91, 0x9c, 0x64, 0x95, 0x4f, 0xf7, 0xd0, 0x4e, 0x6f, 0xd5, 0x0a, 0x5b, 0xfb, 0x1f,
	0xd7, 0x40, 0x1c, 0x2f, 0x72, 0x6a, 0xc6, 0xfb, 0xe5, 0x5e, 0x55, 0xc0, 0xe6, 0xb1, 0xe2, 0xec,
	0xdd, 0x74, 0x92, 0x9e, 0xc7, 0x49, 0x9a, 0x18, 0xe2, 0x9b, 0xd8, 0x08, 0xd1, 0x01, 0x6c, 0xb9,
	0xa0, 0xb6, 0x12, 0xbe, 0x80, 0x96, 0xc8, 0x49, 0xe6, 0xea, 0x60, 0xb7, 0x26, 0x73, 0x6c, 0x2c,
	0xef, 0xdf, 0x85, 0xc0, 0x11, 0x81, 0xd6, 0xa1, 0xf3, 0xfd, 0xe8, 0xdb, 0x97, 0xe3, 0xd1, 0xd3,
	0xed, 0x35, 0xb4, 0x01, 0xc1, 0xcb, 0xf1, 0xb1, 0x91, 0x1a, 0xfb, 0x7f, 0x76, 0x20, 0x38, 0xb4,
	0xfe, 0xe8, 0x17, 0x08, 0xdc, 0x0e, 0x88, 0x3e, 0xa9, 0xac, 0xb5, 0xd2, 0xde, 0xd8, 0xff, 0xf4,
	0xad, 0x76, 0x76, 0x6f, 0x58, 0x43, 0x33, 0xd8, 0x2c, 0xed, 0x72, 0xa8, 0xaa, 0x83, 0x57, 0xed,
	0x90, 0xfd, 0x07, 0x17, 0x33, 0x2e, 0xa2, 0xbd, 0x86, 0xf5, 0xa5, 0x85, 0x0e, 0xdd, 0xab, 0xb9,
	0xe7, 0xb9, 0x48, 0xf7, 0x2f, 0x62, 0xba, 0x9c, 0x55, 0x69, 0x27, 0xab, 0xcc, 0x6a, 0xd5, 0x2e,
	0x58, 0x99, 0xd5, 0xea, 0x35, 0x4f, 0x47, 0x2b, 0xad, 0x65, 0x95, 0xd1, 0x56, 0xad, 0x83, 0x95,
	0xd1, 0x56, 0x6f, 0x7a, 0x6b, 0x28, 0x81, 0x8d, 0xe5, 0xa5, 0x0e, 0x55, 0x31, 0xb3, 0x62, 0x21,
	0xec, 0xef, 0x5d, 0xc8, 0xb6, 0x08, 0xf5, 0x0a, 0x7c, 0x35, 0xfc, 0x50, 0x54, 0xe5, 0x76, 0x36,
	0x5c, 0xfb, 0xb7, 0x6b, 0x6d, 0x0a, 0xc8, 0x9f, 0xa0, 0x6d, 0xfa, 0x08, 0xdd, 0xa9, 0x70, 0x28,
	0xf5, 0x76, 0xff, 0xee, 0x5b, 0xac, 0x0a, 0xe0, 0x63, 0x68, 0xe9, 0x1f, 0x40, 0x54, 0xf7, 0x4b,
	0x57, 0xc0, 0xde, 0xa9, 0x37, 0x72, 0xa8, 0xbf, 0xb6, 0xf5, 0x5f, 0xb6, 0x87, 0xff, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x3a, 0x3f, 0x46, 0x6a, 0xe1, 0x0d, 0x00, 0x00,
}
