// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: proto/billing.proto

package billing

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PortalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PortalRequest) Reset() {
	*x = PortalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_billing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortalRequest) ProtoMessage() {}

func (x *PortalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortalRequest.ProtoReflect.Descriptor instead.
func (*PortalRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{0}
}

type PortalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *PortalResponse) Reset() {
	*x = PortalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_billing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortalResponse) ProtoMessage() {}

func (x *PortalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortalResponse.ProtoReflect.Descriptor instead.
func (*PortalResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{1}
}

func (x *PortalResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Amendment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace    string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PlanID       string `protobuf:"bytes,3,opt,name=planID,proto3" json:"planID,omitempty"`
	PriceID      string `protobuf:"bytes,4,opt,name=priceID,proto3" json:"priceID,omitempty"`
	QuantityFrom int64  `protobuf:"varint,5,opt,name=quantityFrom,proto3" json:"quantityFrom,omitempty"`
	QuantityTo   int64  `protobuf:"varint,6,opt,name=quantityTo,proto3" json:"quantityTo,omitempty"`
	Note         string `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	Created      int64  `protobuf:"varint,8,opt,name=created,proto3" json:"created,omitempty"`
	// customer email, not a stripe customer id
	Customer string `protobuf:"bytes,9,opt,name=customer,proto3" json:"customer,omitempty"`
}

func (x *Amendment) Reset() {
	*x = Amendment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_billing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Amendment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amendment) ProtoMessage() {}

func (x *Amendment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amendment.ProtoReflect.Descriptor instead.
func (*Amendment) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{2}
}

func (x *Amendment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Amendment) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Amendment) GetPlanID() string {
	if x != nil {
		return x.PlanID
	}
	return ""
}

func (x *Amendment) GetPriceID() string {
	if x != nil {
		return x.PriceID
	}
	return ""
}

func (x *Amendment) GetQuantityFrom() int64 {
	if x != nil {
		return x.QuantityFrom
	}
	return 0
}

func (x *Amendment) GetQuantityTo() int64 {
	if x != nil {
		return x.QuantityTo
	}
	return 0
}

func (x *Amendment) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Amendment) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *Amendment) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

type ListAmendmentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Offset    int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit     int64  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListAmendmentsRequest) Reset() {
	*x = ListAmendmentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_billing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAmendmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAmendmentsRequest) ProtoMessage() {}

func (x *ListAmendmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAmendmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAmendmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{3}
}

func (x *ListAmendmentsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListAmendmentsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAmendmentsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListAmendmentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amendments []*Amendment `protobuf:"bytes,1,rep,name=amendments,proto3" json:"amendments,omitempty"`
}

func (x *ListAmendmentsResponse) Reset() {
	*x = ListAmendmentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_billing_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAmendmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAmendmentsResponse) ProtoMessage() {}

func (x *ListAmendmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAmendmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAmendmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{4}
}

func (x *ListAmendmentsResponse) GetAmendments() []*Amendment {
	if x != nil {
		return x.Amendments
	}
	return nil
}

var File_proto_billing_proto protoreflect.FileDescriptor

var file_proto_billing_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x22, 0x0f,
	0x0a, 0x0d, 0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x22, 0x0a, 0x0e, 0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x22, 0xf9, 0x01, 0x0a, 0x09, 0x41, 0x6d, 0x65, 0x6e, 0x64, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x69, 0x63, 0x65, 0x49,
	0x44, 0x12, 0x22, 0x0a, 0x0c, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x46, 0x72, 0x6f,
	0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x54, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x54, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x22,
	0x63, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6d, 0x65, 0x6e, 0x64, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x4c, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6d, 0x65, 0x6e,
	0x64, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32,
	0x0a, 0x0a, 0x61, 0x6d, 0x65, 0x6e, 0x64, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x6d, 0x65,
	0x6e, 0x64, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x61, 0x6d, 0x65, 0x6e, 0x64, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x32, 0x9b, 0x01, 0x0a, 0x07, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x3b,
	0x0a, 0x06, 0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x12, 0x16, 0x2e, 0x62, 0x69, 0x6c, 0x6c, 0x69,
	0x6e, 0x67, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x61,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6d, 0x65, 0x6e, 0x64, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1e, 0x2e,
	0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6d, 0x65, 0x6e,
	0x64, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6d, 0x65, 0x6e,
	0x64, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_billing_proto_rawDescOnce sync.Once
	file_proto_billing_proto_rawDescData = file_proto_billing_proto_rawDesc
)

func file_proto_billing_proto_rawDescGZIP() []byte {
	file_proto_billing_proto_rawDescOnce.Do(func() {
		file_proto_billing_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_billing_proto_rawDescData)
	})
	return file_proto_billing_proto_rawDescData
}

var file_proto_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_billing_proto_goTypes = []interface{}{
	(*PortalRequest)(nil),          // 0: billing.PortalRequest
	(*PortalResponse)(nil),         // 1: billing.PortalResponse
	(*Amendment)(nil),              // 2: billing.Amendment
	(*ListAmendmentsRequest)(nil),  // 3: billing.ListAmendmentsRequest
	(*ListAmendmentsResponse)(nil), // 4: billing.ListAmendmentsResponse
}
var file_proto_billing_proto_depIdxs = []int32{
	2, // 0: billing.ListAmendmentsResponse.amendments:type_name -> billing.Amendment
	0, // 1: billing.Billing.Portal:input_type -> billing.PortalRequest
	3, // 2: billing.Billing.ListAmendments:input_type -> billing.ListAmendmentsRequest
	1, // 3: billing.Billing.Portal:output_type -> billing.PortalResponse
	4, // 4: billing.Billing.ListAmendments:output_type -> billing.ListAmendmentsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_billing_proto_init() }
func file_proto_billing_proto_init() {
	if File_proto_billing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_billing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_billing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_billing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Amendment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_billing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAmendmentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_billing_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAmendmentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_billing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_billing_proto_goTypes,
		DependencyIndexes: file_proto_billing_proto_depIdxs,
		MessageInfos:      file_proto_billing_proto_msgTypes,
	}.Build()
	File_proto_billing_proto = out.File
	file_proto_billing_proto_rawDesc = nil
	file_proto_billing_proto_goTypes = nil
	file_proto_billing_proto_depIdxs = nil
}
