// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/billing.proto

package billing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PortalRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PortalRequest) Reset()         { *m = PortalRequest{} }
func (m *PortalRequest) String() string { return proto.CompactTextString(m) }
func (*PortalRequest) ProtoMessage()    {}
func (*PortalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30210f154235f73e, []int{0}
}

func (m *PortalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortalRequest.Unmarshal(m, b)
}
func (m *PortalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortalRequest.Marshal(b, m, deterministic)
}
func (m *PortalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortalRequest.Merge(m, src)
}
func (m *PortalRequest) XXX_Size() int {
	return xxx_messageInfo_PortalRequest.Size(m)
}
func (m *PortalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PortalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PortalRequest proto.InternalMessageInfo

type PortalResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PortalResponse) Reset()         { *m = PortalResponse{} }
func (m *PortalResponse) String() string { return proto.CompactTextString(m) }
func (*PortalResponse) ProtoMessage()    {}
func (*PortalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_30210f154235f73e, []int{1}
}

func (m *PortalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortalResponse.Unmarshal(m, b)
}
func (m *PortalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortalResponse.Marshal(b, m, deterministic)
}
func (m *PortalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortalResponse.Merge(m, src)
}
func (m *PortalResponse) XXX_Size() int {
	return xxx_messageInfo_PortalResponse.Size(m)
}
func (m *PortalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PortalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PortalResponse proto.InternalMessageInfo

func (m *PortalResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Update struct {
	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace    string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PlanID       string `protobuf:"bytes,3,opt,name=planID,proto3" json:"planID,omitempty"`
	PriceID      string `protobuf:"bytes,4,opt,name=priceID,proto3" json:"priceID,omitempty"`
	QuantityFrom int64  `protobuf:"varint,5,opt,name=quantityFrom,proto3" json:"quantityFrom,omitempty"`
	QuantityTo   int64  `protobuf:"varint,6,opt,name=quantityTo,proto3" json:"quantityTo,omitempty"`
	Note         string `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	Created      int64  `protobuf:"varint,8,opt,name=created,proto3" json:"created,omitempty"`
	// micro customer ID
	CustomerID string `protobuf:"bytes,9,opt,name=customerID,proto3" json:"customerID,omitempty"`
	// micro customer email
	CustomerEmail        string   `protobuf:"bytes,10,opt,name=customerEmail,proto3" json:"customerEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_30210f154235f73e, []int{2}
}

func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (m *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(m, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Update) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Update) GetPlanID() string {
	if m != nil {
		return m.PlanID
	}
	return ""
}

func (m *Update) GetPriceID() string {
	if m != nil {
		return m.PriceID
	}
	return ""
}

func (m *Update) GetQuantityFrom() int64 {
	if m != nil {
		return m.QuantityFrom
	}
	return 0
}

func (m *Update) GetQuantityTo() int64 {
	if m != nil {
		return m.QuantityTo
	}
	return 0
}

func (m *Update) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *Update) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Update) GetCustomerID() string {
	if m != nil {
		return m.CustomerID
	}
	return ""
}

func (m *Update) GetCustomerEmail() string {
	if m != nil {
		return m.CustomerEmail
	}
	return ""
}

type UpdatesRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatesRequest) Reset()         { *m = UpdatesRequest{} }
func (m *UpdatesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatesRequest) ProtoMessage()    {}
func (*UpdatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30210f154235f73e, []int{3}
}

func (m *UpdatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatesRequest.Unmarshal(m, b)
}
func (m *UpdatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatesRequest.Marshal(b, m, deterministic)
}
func (m *UpdatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatesRequest.Merge(m, src)
}
func (m *UpdatesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatesRequest.Size(m)
}
func (m *UpdatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatesRequest proto.InternalMessageInfo

func (m *UpdatesRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *UpdatesRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *UpdatesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type UpdatesResponse struct {
	Updates              []*Update `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdatesResponse) Reset()         { *m = UpdatesResponse{} }
func (m *UpdatesResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatesResponse) ProtoMessage()    {}
func (*UpdatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_30210f154235f73e, []int{4}
}

func (m *UpdatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatesResponse.Unmarshal(m, b)
}
func (m *UpdatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatesResponse.Marshal(b, m, deterministic)
}
func (m *UpdatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatesResponse.Merge(m, src)
}
func (m *UpdatesResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatesResponse.Size(m)
}
func (m *UpdatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatesResponse proto.InternalMessageInfo

func (m *UpdatesResponse) GetUpdates() []*Update {
	if m != nil {
		return m.Updates
	}
	return nil
}

type ApplyRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyRequest) Reset()         { *m = ApplyRequest{} }
func (m *ApplyRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyRequest) ProtoMessage()    {}
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30210f154235f73e, []int{5}
}

func (m *ApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyRequest.Unmarshal(m, b)
}
func (m *ApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyRequest.Marshal(b, m, deterministic)
}
func (m *ApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyRequest.Merge(m, src)
}
func (m *ApplyRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyRequest.Size(m)
}
func (m *ApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyRequest proto.InternalMessageInfo

func (m *ApplyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ApplyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyResponse) Reset()         { *m = ApplyResponse{} }
func (m *ApplyResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyResponse) ProtoMessage()    {}
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_30210f154235f73e, []int{6}
}

func (m *ApplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyResponse.Unmarshal(m, b)
}
func (m *ApplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyResponse.Marshal(b, m, deterministic)
}
func (m *ApplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyResponse.Merge(m, src)
}
func (m *ApplyResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyResponse.Size(m)
}
func (m *ApplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PortalRequest)(nil), "billing.PortalRequest")
	proto.RegisterType((*PortalResponse)(nil), "billing.PortalResponse")
	proto.RegisterType((*Update)(nil), "billing.Update")
	proto.RegisterType((*UpdatesRequest)(nil), "billing.UpdatesRequest")
	proto.RegisterType((*UpdatesResponse)(nil), "billing.UpdatesResponse")
	proto.RegisterType((*ApplyRequest)(nil), "billing.ApplyRequest")
	proto.RegisterType((*ApplyResponse)(nil), "billing.ApplyResponse")
}

func init() {
	proto.RegisterFile("proto/billing.proto", fileDescriptor_30210f154235f73e)
}

var fileDescriptor_30210f154235f73e = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x0f, 0xd2, 0x40,
	0x10, 0xb5, 0x14, 0x5a, 0x19, 0x81, 0x9a, 0x51, 0x61, 0x43, 0x0c, 0x31, 0x1b, 0x0f, 0x78, 0xc1,
	0x04, 0x2f, 0x26, 0x18, 0x13, 0x89, 0x9a, 0x78, 0x33, 0x8d, 0x5e, 0x8c, 0x97, 0x52, 0x16, 0xb3,
	0xc9, 0xb6, 0x5b, 0xda, 0xed, 0x81, 0x7f, 0xe3, 0x4f, 0xf1, 0xa7, 0xd9, 0xee, 0x47, 0xa5, 0xe0,
	0x6d, 0xdf, 0x7b, 0x33, 0x6f, 0x67, 0xdf, 0x0e, 0x3c, 0x29, 0x4a, 0xa9, 0xe4, 0xeb, 0x03, 0x17,
	0x82, 0xe7, 0xbf, 0x36, 0x1a, 0x61, 0x68, 0x21, 0x8d, 0x60, 0xfa, 0x55, 0x96, 0x2a, 0x11, 0x31,
	0x3b, 0xd7, 0xac, 0x52, 0x94, 0xc2, 0xcc, 0x11, 0x55, 0x21, 0xf3, 0x8a, 0xe1, 0x63, 0xf0, 0xeb,
	0x52, 0x10, 0xef, 0x85, 0xb7, 0x1e, 0xc7, 0xed, 0x91, 0xfe, 0x1e, 0x40, 0xf0, 0xbd, 0x38, 0x26,
	0x8a, 0xe1, 0x0c, 0x06, 0xfc, 0x68, 0xb5, 0xe6, 0x84, 0xcf, 0x61, 0x9c, 0x27, 0x59, 0xd3, 0x9a,
	0xa4, 0x8c, 0x0c, 0x34, 0xfd, 0x8f, 0xc0, 0x39, 0x04, 0x85, 0x48, 0xf2, 0x2f, 0x1f, 0x89, 0xaf,
	0x25, 0x8b, 0x90, 0x40, 0x58, 0x94, 0x3c, 0x65, 0x8d, 0x30, 0xd4, 0x82, 0x83, 0x48, 0x61, 0x72,
	0xae, 0x93, 0x5c, 0x71, 0x75, 0xf9, 0x5c, 0xca, 0x8c, 0x8c, 0x1a, 0xd9, 0x8f, 0x7b, 0x1c, 0xae,
	0x00, 0x1c, 0xfe, 0x26, 0x49, 0xa0, 0x2b, 0xae, 0x18, 0x44, 0x18, 0xe6, 0x52, 0x31, 0x12, 0x6a,
	0x6b, 0x7d, 0x6e, 0x6f, 0x4c, 0x4b, 0xd6, 0xbc, 0xe0, 0x48, 0x1e, 0xea, 0x06, 0x07, 0x5b, 0xb7,
	0xb4, 0xae, 0x94, 0xcc, 0x58, 0xd9, 0x8c, 0x33, 0xd6, 0x3d, 0x57, 0x0c, 0xbe, 0x84, 0xa9, 0x43,
	0x9f, 0xb2, 0x84, 0x0b, 0x02, 0xba, 0xa4, 0x4f, 0xd2, 0x9f, 0x30, 0x33, 0x09, 0x55, 0x36, 0xd8,
	0x7e, 0x32, 0xde, 0x7f, 0x92, 0x91, 0xa7, 0x53, 0xc5, 0x94, 0x0e, 0xcd, 0x8f, 0x2d, 0xc2, 0xa7,
	0x30, 0x12, 0x3c, 0xe3, 0x4a, 0x07, 0xe6, 0xc7, 0x06, 0xd0, 0x77, 0x10, 0x75, 0xee, 0xf6, 0x97,
	0x5e, 0x41, 0x58, 0x1b, 0xaa, 0x31, 0xf7, 0xd7, 0x8f, 0xb6, 0xd1, 0xc6, 0x7d, 0xb9, 0x29, 0x8d,
	0x9d, 0x4e, 0x57, 0x30, 0xf9, 0x50, 0x14, 0xe2, 0xe2, 0x26, 0xbb, 0xf9, 0xc3, 0x76, 0x27, 0xac,
	0x6e, 0xbc, 0xb7, 0x7f, 0x3c, 0x08, 0xf7, 0xc6, 0x0c, 0x77, 0x10, 0x98, 0xfd, 0xc0, 0x79, 0x77,
	0x41, 0x6f, 0x83, 0x96, 0x8b, 0x3b, 0xde, 0xd8, 0xd0, 0x07, 0xf8, 0x1e, 0x42, 0x3b, 0x37, 0x2e,
	0x6e, 0xc6, 0x73, 0x39, 0x2d, 0xc9, 0xbd, 0xd0, 0xf5, 0xbf, 0x85, 0x91, 0x9e, 0x0c, 0x9f, 0x75,
	0x45, 0xd7, 0x2f, 0x59, 0xce, 0x6f, 0x69, 0xd7, 0xb9, 0x8f, 0x7e, 0x4c, 0xf5, 0xe6, 0xef, 0x6c,
	0xc1, 0x21, 0xd0, 0xf0, 0xcd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x9c, 0x7a, 0x70, 0x1f,
	0x03, 0x00, 0x00,
}
